/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Nov 21 11:46:30 CST 2007 by MyEclipse Hibernate Tool.
 */
package com.boco.eoms.check.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * A class that represents a row in the TAW_ROOMDUTY_CHECK table.
 * You can customize the behavior of this class by editing the class, {@link TawRoomdutyCheck()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public class TawRoomdutyCheck
        implements Serializable {
    /**
     * The cached hash code value for this instance.  Settting to 0 triggers re-calculation.
     */
    private int hashValue = 0;

    /**
     * The composite primary key value.
     */
    private java.lang.String id;

    /**
     * The value of the simple roomid property.
     */
    private java.lang.String roomid;

    /**
     * The value of the simple checktype property.
     */
    private java.lang.String checktype;

    /**
     * The value of the simple checkdate property.
     */
    private java.lang.String checkdate;

    /**
     * The value of the simple remark property.
     */
    private java.lang.String remark;

    /**
     * The value of the simple state property.
     */
    private java.lang.String state;    //1 表示在使用， 2表示已归档


    private Set addonstable = new HashSet();


    /**
     * Simple constructor of AbstractTawRoomdutyCheck instances.
     */
    public TawRoomdutyCheck() {
    }

    public TawRoomdutyCheck(String roomid, String checktype, String checkdate,
                            String dataurl, String remark, String state) {
        this.roomid = roomid;
        this.checktype = checktype;
        this.checkdate = checkdate;
        this.remark = remark;
        this.state = state;
    }

    /**
     * Constructor of AbstractTawRoomdutyCheck instances given a simple primary
     * key.
     *
     * @param id
     */
    public TawRoomdutyCheck(java.lang.String id) {
        this.setId(id);
    }

    /**
     * Return the simple primary key value that identifies this object.
     *
     * @return java.lang.Long
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     *
     * @param id
     */
    public void setId(java.lang.String id) {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Return the value of the ROOMID column.
     *
     * @return java.lang.Long
     */
    public java.lang.String getRoomid() {
        return this.roomid;
    }

    /**
     * Set the value of the ROOMID column.
     *
     * @param roomid
     */
    public void setRoomid(java.lang.String roomid) {
        this.roomid = roomid;
    }

    /**
     * Return the value of the CHECKTYPE column.
     *
     * @return java.lang.String
     */
    public java.lang.String getChecktype() {
        return this.checktype;
    }

    /**
     * Set the value of the CHECKTYPE column.
     *
     * @param checktype
     */
    public void setChecktype(java.lang.String checktype) {
        this.checktype = checktype;
    }

    /**
     * Return the value of the CHECKDATE column.
     *
     * @return java.lang.String
     */
    public java.lang.String getCheckdate() {
        return this.checkdate;
    }

    /**
     * Set the value of the CHECKDATE column.
     *
     * @param checkdate
     */
    public void setCheckdate(java.lang.String checkdate) {
        this.checkdate = checkdate;
    }

    /**
     * Return the value of the REMARK column.
     *
     * @return java.lang.String
     */
    public java.lang.String getRemark() {
        return this.remark;
    }

    /**
     * Set the value of the REMARK column.
     *
     * @param remark
     */
    public void setRemark(java.lang.String remark) {
        this.remark = remark;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     *
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs) {
        if (rhs == null)
            return false;
        if (!(rhs instanceof TawRoomdutyCheck))
            return false;
        TawRoomdutyCheck that = (TawRoomdutyCheck) rhs;
        if (this.getId() == null || that.getId() == null)
            return false;
        return (this.getId().equals(that.getId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     *
     * @return int
     */
    public int hashCode() {
        if (this.hashValue == 0) {
            int result = 17;
            int idValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + idValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }

    public Set getAddonstable() {
        return addonstable;
    }

    public void setAddonstable(Set addonstable) {
        this.addonstable = addonstable;
    }

    public java.lang.String getState() {
        return state;
    }

    public void setState(java.lang.String state) {
        this.state = state;
    }
}
