package com.boco.eoms.bureaudata.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="tawBureauDataForm"
 */
public class TawBureauDataForm
        extends BaseForm
        implements java.io.Serializable {

    protected String auditman;

    protected String bigNet;

    protected String content;

    protected String crusdata;

    protected String cruser;

    protected String data;

    protected String factory;

    protected String id;

    protected String net;

    protected String producer;

    protected String remark;

    protected String title;

    protected String type;

    protected String auditmanName;

    protected String producerName;

    public String getAuditmanName() {
        return auditmanName;
    }

    public void setAuditmanName(String auditmanName) {
        this.auditmanName = auditmanName;
    }

    public String getProducerName() {
        return producerName;
    }

    public void setProducerName(String producerName) {
        this.producerName = producerName;
    }

    /**
     * Default empty constructor.
     */
    public TawBureauDataForm() {
    }

    public String getAuditman() {
        return this.auditman;
    }

    /**
     *
     */

    public void setAuditman(String auditman) {
        this.auditman = auditman;
    }

    public String getBigNet() {
        return this.bigNet;
    }

    /**
     *
     */

    public void setBigNet(String bigNet) {
        this.bigNet = bigNet;
    }

    public String getContent() {
        return this.content;
    }

    /**
     *
     */

    public void setContent(String content) {
        this.content = content;
    }

    public String getCrusdata() {
        return this.crusdata;
    }

    /**
     *
     */

    public void setCrusdata(String crusdata) {
        this.crusdata = crusdata;
    }

    public String getCruser() {
        return this.cruser;
    }

    /**
     *
     */

    public void setCruser(String cruser) {
        this.cruser = cruser;
    }

    public String getData() {
        return this.data;
    }

    /**
     *
     */

    public void setData(String data) {
        this.data = data;
    }

    public String getFactory() {
        return this.factory;
    }

    /**
     *
     */

    public void setFactory(String factory) {
        this.factory = factory;
    }

    public String getId() {
        return this.id;
    }

    /**
     *
     */

    public void setId(String id) {
        this.id = id;
    }

    public String getNet() {
        return this.net;
    }

    /**
     *
     */

    public void setNet(String net) {
        this.net = net;
    }

    public String getProducer() {
        return this.producer;
    }

    /**
     *
     */

    public void setProducer(String producer) {
        this.producer = producer;
    }

    public String getRemark() {
        return this.remark;
    }

    /**
     *
     */

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getTitle() {
        return this.title;
    }

    /**
     *
     */

    public void setTitle(String title) {
        this.title = title;
    }

    public String getType() {
        return this.type;
    }

    /**
     *
     */

    public void setType(String type) {
        this.type = type;
    }

        /* To add non XDoclet-generated methods, create a file named
           xdoclet-TawBureauDataForm.java 
           containing the additional code and place it in your metadata/web directory.
        */

    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     * javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

}
