package com.boco.eoms.parter.baseinfo.basemetermgr.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="basemetermgrForm" 
 */
public class BasemetermgrForm
    extends    BaseForm
    implements java.io.Serializable
{

    protected String id;

    protected String maintenUnitIdVal;

    protected String maintenUnitIdRem;

    protected String desktopComputerVal;

    protected String desktopComputerRem;

    protected String faxVal;

    protected String faxRem;

    protected String fixedPhoneVal;

    protected String fixedPhoneRem;

    protected String moveTestPhoneVal;

    protected String moveTestPhoneRem;

    protected String lineTesterVal;

    protected String lineTesterRem;

    protected String terraBlockTesterVal;

    protected String terraBlockTesterRem;

    protected String cellTesterVal;

    protected String cellTesterRem;

    protected String maintenanceToolsVal;

    protected String maintenanceToolsRem;

    protected String maintenanceCarsVal;

    protected String maintenanceCarsRem;

    protected String multimeterVal;

    protected String multimeterRem;

    protected String ACDCclampMeterVal;

    protected String ACDCclampMeterRem;

    protected String twoMInstrumentVal;

    protected String twoMInstrumentRem;

    protected String antennaAngleGaugeVal;

    protected String antennaAngleGaugeRem;

    protected String telescopeVal;

    protected String telescopeRem;

    protected String digitalCameraVal;

    protected String digitalCameraRem;

    protected String gradienterVal;

    protected String gradienterRem;

    protected String GPSLocatorVal;

    protected String GPSLocatorRem;

    protected String infraredThermoscopeVal;

    protected String infraredThermoscopeRem;

    protected String notebookPCVal;

    protected String notebookPCRem;

    protected String mobileGpsVal;

    protected String mobileGps;

    protected String remark;

    /** Default empty constructor. */
    public BasemetermgrForm() {}

    public String getId()
    {
        return this.id;
    }
   /**
    */

    public void setId( String id )
    {
        this.id = id;
    }

    public String getMaintenUnitIdVal()
    {
        return this.maintenUnitIdVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMaintenUnitIdVal( String maintenUnitIdVal )
    {
        this.maintenUnitIdVal = maintenUnitIdVal;
    }

    public String getMaintenUnitIdRem()
    {
        return this.maintenUnitIdRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMaintenUnitIdRem( String maintenUnitIdRem )
    {
        this.maintenUnitIdRem = maintenUnitIdRem;
    }

    public String getDesktopComputerVal()
    {
        return this.desktopComputerVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setDesktopComputerVal( String desktopComputerVal )
    {
        this.desktopComputerVal = desktopComputerVal;
    }

    public String getDesktopComputerRem()
    {
        return this.desktopComputerRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setDesktopComputerRem( String desktopComputerRem )
    {
        this.desktopComputerRem = desktopComputerRem;
    }

    public String getFaxVal()
    {
        return this.faxVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setFaxVal( String faxVal )
    {
        this.faxVal = faxVal;
    }

    public String getFaxRem()
    {
        return this.faxRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setFaxRem( String faxRem )
    {
        this.faxRem = faxRem;
    }

    public String getFixedPhoneVal()
    {
        return this.fixedPhoneVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setFixedPhoneVal( String fixedPhoneVal )
    {
        this.fixedPhoneVal = fixedPhoneVal;
    }

    public String getFixedPhoneRem()
    {
        return this.fixedPhoneRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setFixedPhoneRem( String fixedPhoneRem )
    {
        this.fixedPhoneRem = fixedPhoneRem;
    }

    public String getMoveTestPhoneVal()
    {
        return this.moveTestPhoneVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMoveTestPhoneVal( String moveTestPhoneVal )
    {
        this.moveTestPhoneVal = moveTestPhoneVal;
    }

    public String getMoveTestPhoneRem()
    {
        return this.moveTestPhoneRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMoveTestPhoneRem( String moveTestPhoneRem )
    {
        this.moveTestPhoneRem = moveTestPhoneRem;
    }

    public String getLineTesterVal()
    {
        return this.lineTesterVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setLineTesterVal( String lineTesterVal )
    {
        this.lineTesterVal = lineTesterVal;
    }

    public String getLineTesterRem()
    {
        return this.lineTesterRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setLineTesterRem( String lineTesterRem )
    {
        this.lineTesterRem = lineTesterRem;
    }

    public String getTerraBlockTesterVal()
    {
        return this.terraBlockTesterVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setTerraBlockTesterVal( String terraBlockTesterVal )
    {
        this.terraBlockTesterVal = terraBlockTesterVal;
    }

    public String getTerraBlockTesterRem()
    {
        return this.terraBlockTesterRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setTerraBlockTesterRem( String terraBlockTesterRem )
    {
        this.terraBlockTesterRem = terraBlockTesterRem;
    }

    public String getCellTesterVal()
    {
        return this.cellTesterVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setCellTesterVal( String cellTesterVal )
    {
        this.cellTesterVal = cellTesterVal;
    }

    public String getCellTesterRem()
    {
        return this.cellTesterRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setCellTesterRem( String cellTesterRem )
    {
        this.cellTesterRem = cellTesterRem;
    }

    public String getMaintenanceToolsVal()
    {
        return this.maintenanceToolsVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMaintenanceToolsVal( String maintenanceToolsVal )
    {
        this.maintenanceToolsVal = maintenanceToolsVal;
    }

    public String getMaintenanceToolsRem()
    {
        return this.maintenanceToolsRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMaintenanceToolsRem( String maintenanceToolsRem )
    {
        this.maintenanceToolsRem = maintenanceToolsRem;
    }

    public String getMaintenanceCarsVal()
    {
        return this.maintenanceCarsVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMaintenanceCarsVal( String maintenanceCarsVal )
    {
        this.maintenanceCarsVal = maintenanceCarsVal;
    }

    public String getMaintenanceCarsRem()
    {
        return this.maintenanceCarsRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMaintenanceCarsRem( String maintenanceCarsRem )
    {
        this.maintenanceCarsRem = maintenanceCarsRem;
    }

    public String getMultimeterVal()
    {
        return this.multimeterVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMultimeterVal( String multimeterVal )
    {
        this.multimeterVal = multimeterVal;
    }

    public String getMultimeterRem()
    {
        return this.multimeterRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMultimeterRem( String multimeterRem )
    {
        this.multimeterRem = multimeterRem;
    }

    public String getACDCclampMeterVal()
    {
        return this.ACDCclampMeterVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setACDCclampMeterVal( String ACDCclampMeterVal )
    {
        this.ACDCclampMeterVal = ACDCclampMeterVal;
    }

    public String getACDCclampMeterRem()
    {
        return this.ACDCclampMeterRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setACDCclampMeterRem( String ACDCclampMeterRem )
    {
        this.ACDCclampMeterRem = ACDCclampMeterRem;
    }

    public String getTwoMInstrumentVal()
    {
        return this.twoMInstrumentVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setTwoMInstrumentVal( String twoMInstrumentVal )
    {
        this.twoMInstrumentVal = twoMInstrumentVal;
    }

    public String getTwoMInstrumentRem()
    {
        return this.twoMInstrumentRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setTwoMInstrumentRem( String twoMInstrumentRem )
    {
        this.twoMInstrumentRem = twoMInstrumentRem;
    }

    public String getAntennaAngleGaugeVal()
    {
        return this.antennaAngleGaugeVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setAntennaAngleGaugeVal( String antennaAngleGaugeVal )
    {
        this.antennaAngleGaugeVal = antennaAngleGaugeVal;
    }

    public String getAntennaAngleGaugeRem()
    {
        return this.antennaAngleGaugeRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setAntennaAngleGaugeRem( String antennaAngleGaugeRem )
    {
        this.antennaAngleGaugeRem = antennaAngleGaugeRem;
    }

    public String getTelescopeVal()
    {
        return this.telescopeVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setTelescopeVal( String telescopeVal )
    {
        this.telescopeVal = telescopeVal;
    }

    public String getTelescopeRem()
    {
        return this.telescopeRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setTelescopeRem( String telescopeRem )
    {
        this.telescopeRem = telescopeRem;
    }

    public String getDigitalCameraVal()
    {
        return this.digitalCameraVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setDigitalCameraVal( String digitalCameraVal )
    {
        this.digitalCameraVal = digitalCameraVal;
    }

    public String getDigitalCameraRem()
    {
        return this.digitalCameraRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setDigitalCameraRem( String digitalCameraRem )
    {
        this.digitalCameraRem = digitalCameraRem;
    }

    public String getGradienterVal()
    {
        return this.gradienterVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setGradienterVal( String gradienterVal )
    {
        this.gradienterVal = gradienterVal;
    }

    public String getGradienterRem()
    {
        return this.gradienterRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setGradienterRem( String gradienterRem )
    {
        this.gradienterRem = gradienterRem;
    }

    public String getGPSLocatorVal()
    {
        return this.GPSLocatorVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setGPSLocatorVal( String GPSLocatorVal )
    {
        this.GPSLocatorVal = GPSLocatorVal;
    }

    public String getGPSLocatorRem()
    {
        return this.GPSLocatorRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setGPSLocatorRem( String GPSLocatorRem )
    {
        this.GPSLocatorRem = GPSLocatorRem;
    }

    public String getInfraredThermoscopeVal()
    {
        return this.infraredThermoscopeVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setInfraredThermoscopeVal( String infraredThermoscopeVal )
    {
        this.infraredThermoscopeVal = infraredThermoscopeVal;
    }

    public String getInfraredThermoscopeRem()
    {
        return this.infraredThermoscopeRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setInfraredThermoscopeRem( String infraredThermoscopeRem )
    {
        this.infraredThermoscopeRem = infraredThermoscopeRem;
    }

    public String getNotebookPCVal()
    {
        return this.notebookPCVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setNotebookPCVal( String notebookPCVal )
    {
        this.notebookPCVal = notebookPCVal;
    }

    public String getNotebookPCRem()
    {
        return this.notebookPCRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setNotebookPCRem( String notebookPCRem )
    {
        this.notebookPCRem = notebookPCRem;
    }

    public String getMobileGpsVal()
    {
        return this.mobileGpsVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMobileGpsVal( String mobileGpsVal )
    {
        this.mobileGpsVal = mobileGpsVal;
    }

    public String getMobileGps()
    {
        return this.mobileGps;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMobileGps( String mobileGps )
    {
        this.mobileGps = mobileGps;
    }

    public String getRemark()
    {
        return this.remark;
    }
   /**
    * @struts.validator type="required"
    */

    public void setRemark( String remark )
    {
        this.remark = remark;
    }

        /* To add non XDoclet-generated methods, create a file named
           xdoclet-BasemetermgrForm.java 
           containing the additional code and place it in your metadata/web directory.
        */
    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     *                                                javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

}
