package com.boco.eoms.parter.baseinfo.metermgr.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="metermgrForm" 
 */
public class MetermgrForm
    extends    BaseForm
    implements java.io.Serializable
{

    protected String id;

    protected String maintenUnitId;

    protected String meterName;

    protected String meterSort;

    protected String meterNumber;

    protected String useSummarize;

    /** Default empty constructor. */
    public MetermgrForm() {}

    public String getId()
    {
        return this.id;
    }
   /**
    */

    public void setId( String id )
    {
        this.id = id;
    }

    public String getMaintenUnitId()
    {
        return this.maintenUnitId;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMaintenUnitId( String maintenUnitId )
    {
        this.maintenUnitId = maintenUnitId;
    }

    public String getMeterName()
    {
        return this.meterName;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMeterName( String meterName )
    {
        this.meterName = meterName;
    }

    public String getMeterSort()
    {
        return this.meterSort;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMeterSort( String meterSort )
    {
        this.meterSort = meterSort;
    }

    public String getMeterNumber()
    {
        return this.meterNumber;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMeterNumber( String meterNumber )
    {
        this.meterNumber = meterNumber;
    }

    public String getUseSummarize()
    {
        return this.useSummarize;
    }
   /**
    * @struts.validator type="required"
    */

    public void setUseSummarize( String useSummarize )
    {
        this.useSummarize = useSummarize;
    }

        /* To add non XDoclet-generated methods, create a file named
           xdoclet-MetermgrForm.java 
           containing the additional code and place it in your metadata/web directory.
        */
    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     *                                                javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

}
