package com.boco.eoms.taskplan.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="taskplanForm" 
 */
public class TaskplanForm
    extends    BaseForm
    implements java.io.Serializable
{

    protected String deptid;

    protected String id;

    protected String insert_time;

    protected String month_mark;

    protected String project_decompose;

    protected String project_name;

    protected String serial_mark;

    protected String stakeholders;

    protected String task_complete;

    protected String task_decompose;

    protected String task_plan;
    
    private String deptName;
	
	private String stakeholdersName;

    /** Default empty constructor. */
    public TaskplanForm() {}

    public String getDeptid()
    {
        return this.deptid;
    }
   /**
    */

    public void setDeptid( String deptid )
    {
        this.deptid = deptid;
    }

    public String getId()
    {
        return this.id;
    }
   /**
    */

    public void setId( String id )
    {
        this.id = id;
    }

    public String getInsert_time()
    {
        return this.insert_time;
    }
   /**
    */

    public void setInsert_time( String insert_time )
    {
        this.insert_time = insert_time;
    }

    public String getMonth_mark()
    {
        return this.month_mark;
    }
   /**
    */

    public void setMonth_mark( String month_mark )
    {
        this.month_mark = month_mark;
    }

    public String getProject_decompose()
    {
        return this.project_decompose;
    }
   /**
    */

    public void setProject_decompose( String project_decompose )
    {
        this.project_decompose = project_decompose;
    }

    public String getProject_name()
    {
        return this.project_name;
    }
   /**
    */

    public void setProject_name( String project_name )
    {
        this.project_name = project_name;
    }

    public String getSerial_mark()
    {
        return this.serial_mark;
    }
   /**
    */

    public void setSerial_mark( String serial_mark )
    {
        this.serial_mark = serial_mark;
    }

    public String getStakeholders()
    {
        return this.stakeholders;
    }
   /**
    */

    public void setStakeholders( String stakeholders )
    {
        this.stakeholders = stakeholders;
    }

    public String getTask_complete()
    {
        return this.task_complete;
    }
   /**
    */

    public void setTask_complete( String task_complete )
    {
        this.task_complete = task_complete;
    }

    public String getTask_decompose()
    {
        return this.task_decompose;
    }
   /**
    */

    public void setTask_decompose( String task_decompose )
    {
        this.task_decompose = task_decompose;
    }

    public String getTask_plan()
    {
        return this.task_plan;
    }
   /**
    */

    public void setTask_plan( String task_plan )
    {
        this.task_plan = task_plan;
    }

        /* To add non XDoclet-generated methods, create a file named
           xdoclet-TaskplanForm.java 
           containing the additional code and place it in your metadata/web directory.
        */
    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     *                                                javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

	public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getStakeholdersName() {
		return stakeholdersName;
	}

	public void setStakeholdersName(String stakeholdersName) {
		this.stakeholdersName = stakeholdersName;
	}

}
