package com.boco.eoms.parter.baseinfo.pnrcompact.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="pnrcompactForm" 
 */
public class PnrcompactForm
    extends    BaseForm
    implements java.io.Serializable
{

    protected String id;

    protected String compactNumVal;

    protected String compactNumRem;

    protected String compactNameVal;

    protected String compactNameRem;

    protected String conmpactUnitVal;
    
    protected String conmpactUnitValId;

    protected String conmpactUnitRem;

    protected String compactContentVal;

    protected String compactContentRem;

    protected String compactPlaceVal;

    protected String compactPlaceRem;

    protected String projectMeasureVal;

    protected String projectMeasureRem;

    protected String unitPriceVal;

    protected String unitPriceRem;

    protected String compactMoneyVal;

    protected String compactMoneyRem;

    protected String paymentModeVal;

    protected String paymentModeRem;

    protected String compactSignedDateVal;

    protected String compactSignedDateRem;

    protected String compactValidityVal;

    protected String compactValidityRem;

    protected String remarkVal;

    protected String remarkRem;

    /** Default empty constructor. */
    public PnrcompactForm() {}

    public String getId()
    {
        return this.id;
    }
   /**
    */

    public void setId( String id )
    {
        this.id = id;
    }
    
    

	public String getConmpactUnitValId() {
		return conmpactUnitValId;
	}

	public void setConmpactUnitValId(String conmpactUnitValId) {
		this.conmpactUnitValId = conmpactUnitValId;
	}

	public String getCompactNumVal()
    {
        return this.compactNumVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setCompactNumVal( String compactNumVal )
    {
        this.compactNumVal = compactNumVal;
    }

    public String getCompactNumRem()
    {
        return this.compactNumRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setCompactNumRem( String compactNumRem )
    {
        this.compactNumRem = compactNumRem;
    }

    public String getCompactNameVal()
    {
        return this.compactNameVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setCompactNameVal( String compactNameVal )
    {
        this.compactNameVal = compactNameVal;
    }

    public String getCompactNameRem()
    {
        return this.compactNameRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setCompactNameRem( String compactNameRem )
    {
        this.compactNameRem = compactNameRem;
    }

    public String getConmpactUnitVal()
    {
        return this.conmpactUnitVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setConmpactUnitVal( String conmpactUnitVal )
    {
        this.conmpactUnitVal = conmpactUnitVal;
    }

    public String getConmpactUnitRem()
    {
        return this.conmpactUnitRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setConmpactUnitRem( String conmpactUnitRem )
    {
        this.conmpactUnitRem = conmpactUnitRem;
    }

    public String getCompactContentVal()
    {
        return this.compactContentVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setCompactContentVal( String compactContentVal )
    {
        this.compactContentVal = compactContentVal;
    }

    public String getCompactContentRem()
    {
        return this.compactContentRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setCompactContentRem( String compactContentRem )
    {
        this.compactContentRem = compactContentRem;
    }

    public String getCompactPlaceVal()
    {
        return this.compactPlaceVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setCompactPlaceVal( String compactPlaceVal )
    {
        this.compactPlaceVal = compactPlaceVal;
    }

    public String getCompactPlaceRem()
    {
        return this.compactPlaceRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setCompactPlaceRem( String compactPlaceRem )
    {
        this.compactPlaceRem = compactPlaceRem;
    }

    public String getProjectMeasureVal()
    {
        return this.projectMeasureVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setProjectMeasureVal( String projectMeasureVal )
    {
        this.projectMeasureVal = projectMeasureVal;
    }

    public String getProjectMeasureRem()
    {
        return this.projectMeasureRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setProjectMeasureRem( String projectMeasureRem )
    {
        this.projectMeasureRem = projectMeasureRem;
    }

    public String getUnitPriceVal()
    {
        return this.unitPriceVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setUnitPriceVal( String unitPriceVal )
    {
        this.unitPriceVal = unitPriceVal;
    }

    public String getUnitPriceRem()
    {
        return this.unitPriceRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setUnitPriceRem( String unitPriceRem )
    {
        this.unitPriceRem = unitPriceRem;
    }

    public String getCompactMoneyVal()
    {
        return this.compactMoneyVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setCompactMoneyVal( String compactMoneyVal )
    {
        this.compactMoneyVal = compactMoneyVal;
    }

    public String getCompactMoneyRem()
    {
        return this.compactMoneyRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setCompactMoneyRem( String compactMoneyRem )
    {
        this.compactMoneyRem = compactMoneyRem;
    }

    public String getPaymentModeVal()
    {
        return this.paymentModeVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setPaymentModeVal( String paymentModeVal )
    {
        this.paymentModeVal = paymentModeVal;
    }

    public String getPaymentModeRem()
    {
        return this.paymentModeRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setPaymentModeRem( String paymentModeRem )
    {
        this.paymentModeRem = paymentModeRem;
    }

    public String getCompactSignedDateVal()
    {
        return this.compactSignedDateVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setCompactSignedDateVal( String compactSignedDateVal )
    {
        this.compactSignedDateVal = compactSignedDateVal;
    }

    public String getCompactSignedDateRem()
    {
        return this.compactSignedDateRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setCompactSignedDateRem( String compactSignedDateRem )
    {
        this.compactSignedDateRem = compactSignedDateRem;
    }

    public String getCompactValidityVal()
    {
        return this.compactValidityVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setCompactValidityVal( String compactValidityVal )
    {
        this.compactValidityVal = compactValidityVal;
    }

    public String getCompactValidityRem()
    {
        return this.compactValidityRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setCompactValidityRem( String compactValidityRem )
    {
        this.compactValidityRem = compactValidityRem;
    }

    public String getRemarkVal()
    {
        return this.remarkVal;
    }
   /**
    * @struts.validator type="required"
    */

    public void setRemarkVal( String remarkVal )
    {
        this.remarkVal = remarkVal;
    }

    public String getRemarkRem()
    {
        return this.remarkRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setRemarkRem( String remarkRem )
    {
        this.remarkRem = remarkRem;
    }

        /* To add non XDoclet-generated methods, create a file named
           xdoclet-PnrcompactForm.java 
           containing the additional code and place it in your metadata/web directory.
        */
    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     *                                                javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

}
