package com.boco.eoms.commons.system.dict.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;

import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="tawSystemDictTypeForm" 
 */
public class TawSystemDictTypeForm
    extends    BaseForm
    implements java.io.Serializable
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	protected String id;

    protected String dictId;

    protected String dictCode;

    protected String dictName;

    protected String moduleId;

    protected String moduleName;

    protected String dictRemark;

    protected String parentDictId = "-1";
    protected String parentDictName;

    protected String sysType = "1";
    
    protected String leaf;

    public String getLeaf() {
		return leaf;
	}

	public void setLeaf(String leaf) {
		this.leaf = leaf;
	}

	/** Default empty constructor. */
    public TawSystemDictTypeForm() {}

    public String getId()
    {
        return this.id;
    }
   /**
    */

    public void setId( String id )
    {
        this.id = id;
    }

    public String getDictName()
    {
        return this.dictName;
    }
   /**
    * @struts.validator type="required"
    */

    public void setDictName( String dictName )
    {
        this.dictName = dictName;
    }

    public String getModuleId()
    {
        return this.moduleId;
    }
   /**
    * @struts.validator type="required"
    */

    public void setModuleId( String moduleId )
    {
        this.moduleId = moduleId;
    }

    public String getModuleName()
    {
        return this.moduleName;
    }
   /**
    * @struts.validator type="required"
    */

    public void setModuleName( String moduleName )
    {
        this.moduleName = moduleName;
    }

    public String getDictRemark()
    {
        return this.dictRemark;
    }
   /**
    */

    public void setDictRemark( String dictRemark )
    {
        this.dictRemark = dictRemark;
    }

        /* To add non XDoclet-generated methods, create a file named
           xdoclet-TawSystemDictTypeForm.java 
           containing the additional code and place it in your metadata/web directory.
        */
    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     *                                                javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

    public String getDictId() {
        return dictId;
    }

    public void setDictId(String dictId) {
        this.dictId = dictId;
    }

    public String getParentDictId() {
        return parentDictId;
    }

    public void setParentDictId(String parentDictId) {
        this.parentDictId = parentDictId;
    }

    public String getSysType() {
        return sysType;
    }

    public void setSysType(String sysType) {
        this.sysType = sysType;
    }

	public String getDictCode() {
		return dictCode;
	}

	public void setDictCode(String dictCode) {
		this.dictCode = dictCode;
	}

	public String getParentDictName() {
		return parentDictName;
	}

	public void setParentDictName(String parentDictName) {
		this.parentDictName = parentDictName;
	}

}
