package com.boco.eoms.duty.model;


/**
 * AbstractTawRmDutyeventPubId generated by MyEclipse Persistence Tools
 */

public class TawRmDutyEventPub {

	// Fields

	private String id;

	private String flag;

	private String eventid;

	private String title;

	private String datatime;

	private String starttime;

	private String endtime;

	private int oid;

	private String man;

	private String pubstatus;

	// Constructors

	/** default constructor */
	public TawRmDutyEventPub() {
	}



	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public String getEventid() {
		return this.eventid;
	}

	public void setEventid(String eventid) {
		this.eventid = eventid;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDatatime() {
		return this.datatime;
	}

	public void setDatatime(String datatime) {
		this.datatime = datatime;
	}

	public String getStarttime() {
		return this.starttime;
	}

	public void setStarttime(String starttime) {
		this.starttime = starttime;
	}

	public String getEndtime() {
		return this.endtime;
	}

	public void setEndtime(String endtime) {
		this.endtime = endtime;
	}



	public int getOid() {
		return oid;
	}



	public void setOid(int oid) {
		this.oid = oid;
	}



	public String getMan() {
		return this.man;
	}

	public void setMan(String man) {
		this.man = man;
	}

	public String getPubstatus() {
		return this.pubstatus;
	}

	public void setPubstatus(String pubstatus) {
		this.pubstatus = pubstatus;
	}



	public boolean equals(Object o) {
		// TODO Auto-generated method stub
		return false;
	}

	

}