package com.boco.eoms.commons.sample.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="sampleTableForm" 
 */
public class SampleTableForm
    extends    BaseForm
    implements java.io.Serializable
{

    protected String colAddr;

    protected String colName;

    protected String id;

    /** Default empty constructor. */
    public SampleTableForm() {}

    public String getColAddr()
    {
        return this.colAddr;
    }
   /**
    * @struts.validator type="required"
    */

    public void setColAddr( String colAddr )
    {
        this.colAddr = colAddr;
    }

    public String getColName()
    {
        return this.colName;
    }
   /**
    * @struts.validator type="required"
    */

    public void setColName( String colName )
    {
        this.colName = colName;
    }

    public String getId()
    {
        return this.id;
    }
   /**
    */

    public void setId( String id )
    {
        this.id = id;
    }

        /* To add non XDoclet-generated methods, create a file named
           xdoclet-SampleTableForm.java 
           containing the additional code and place it in your metadata/web directory.
        */
    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     *                                                javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

}
