package com.boco.eoms.sheet.tool.access.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="tawSheetAccessForm" 
 */
public class TawSheetAccessForm
    extends    BaseForm
    implements java.io.Serializable
{

    protected String accesss;

    protected String id;

    protected String processname;

    protected String taskname;

    protected String accessid;

    protected String leaf;

    protected String ordercode;

    protected String parAccessid;

    protected String remark;

    /** Default empty constructor. */
    public TawSheetAccessForm() {}

    public String getAccesss()
    {
        return this.accesss;
    }
   /**
    */

    public void setAccesss( String accesss )
    {
        this.accesss = accesss;
    }

    public String getId()
    {
        return this.id;
    }
   /**
    */

    public void setId( String id )
    {
        this.id = id;
    }

    public String getProcessname()
    {
        return this.processname;
    }
   /**
    */

    public void setProcessname( String processname )
    {
        this.processname = processname;
    }

    public String getTaskname()
    {
        return this.taskname;
    }
   /**
    */

    public void setTaskname( String taskname )
    {
        this.taskname = taskname;
    }

    public String getAccessid()
    {
        return this.accessid;
    }
   /**
    */

    public void setAccessid( String accessid )
    {
        this.accessid = accessid;
    }

    public String getLeaf()
    {
        return this.leaf;
    }
   /**
    */

    public void setLeaf( String leaf )
    {
        this.leaf = leaf;
    }

    public String getOrdercode()
    {
        return this.ordercode;
    }
   /**
    */

    public void setOrdercode( String ordercode )
    {
        this.ordercode = ordercode;
    }

    public String getParAccessid()
    {
        return this.parAccessid;
    }
   /**
    */

    public void setParAccessid( String parAccessid )
    {
        this.parAccessid = parAccessid;
    }

    public String getRemark()
    {
        return this.remark;
    }
   /**
    */

    public void setRemark( String remark )
    {
        this.remark = remark;
    }

        /* To add non XDoclet-generated methods, create a file named
           xdoclet-TawSheetAccessForm.java 
           containing the additional code and place it in your metadata/web directory.
        */
    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     *                                                javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

}
