package com.boco.eoms.commons.system.role.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="tawSystemRoleTypeForm" 
 */
public class TawSystemRoleTypeForm
    extends    BaseForm
    implements java.io.Serializable
{

    protected String deleted;

    protected String notes;

    protected String roletype_id;

    protected String roletype_name;

    protected String system_name;

    /** Default empty constructor. */
    public TawSystemRoleTypeForm() {}

    public String getDeleted()
    {
        return this.deleted;
    }
   /**
    * @struts.validator type="required"
    */

    public void setDeleted( String deleted )
    {
        this.deleted = deleted;
    }

    public String getNotes()
    {
        return this.notes;
    }
   /**
    * @struts.validator type="required"
    */

    public void setNotes( String notes )
    {
        this.notes = notes;
    }

    public String getRoletype_id()
    {
        return this.roletype_id;
    }
   /**
    */

    public void setRoletype_id( String roletype_id )
    {
        this.roletype_id = roletype_id;
    }

    public String getRoletype_name()
    {
        return this.roletype_name;
    }
   /**
    * @struts.validator type="required"
    */

    public void setRoletype_name( String roletype_name )
    {
        this.roletype_name = roletype_name;
    }

    public String getSystem_name()
    {
        return this.system_name;
    }
   /**
    * @struts.validator type="required"
    */

    public void setSystem_name( String system_name )
    {
        this.system_name = system_name;
    }

        /* To add non XDoclet-generated methods, create a file named
           xdoclet-TawSystemRoleTypeForm.java 
           containing the additional code and place it in your metadata/web directory.
        */
    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     *                                                javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

}
