package com.boco.eoms.commons.system.role.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="tawSystemSubRoleForm" 
 */
public class TawSystemSubRoleForm
    extends    BaseForm
    implements java.io.Serializable
{

    protected String area;

    protected long deptId;

    protected String id;

    protected int leaf;

    protected int limitCount;

    protected long parentId;

    protected long roleId;

    protected String subRoleName;

    protected String type1;

    protected String type2;

    protected String type3;
    
    protected String userId;

    public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	/** Default empty constructor. */
    public TawSystemSubRoleForm() {}

    public String getArea()
    {
        return this.area;
    }
   /**
    * @struts.validator type="required"
    */

    public void setArea( String area )
    {
        this.area = area;
    }

    public long getDeptId()
    {
        return this.deptId;
    }
   /**
    * @struts.validator type="required"
    */

    public void setDeptId( long deptId )
    {
        this.deptId = deptId;
    }

    public String getId()
    {
        return this.id;
    }
   /**
    */

    public void setId( String id )
    {
        this.id = id;
    }

    public int getLeaf()
    {
        return this.leaf;
    }
   /**
    * @struts.validator type="required"
    */

    public void setLeaf( int leaf )
    {
        this.leaf = leaf;
    }

    public int getLimitCount()
    {
        return this.limitCount;
    }
   /**
    * @struts.validator type="required"
    */

    public void setLimitCount( int limitCount )
    {
        this.limitCount = limitCount;
    }

    public long getParentId()
    {
        return this.parentId;
    }
   /**
    * @struts.validator type="required"
    */

    public void setParentId( long parentId )
    {
        this.parentId = parentId;
    }

    public long getRoleId()
    {
        return this.roleId;
    }
   /**
    * @struts.validator type="required"
    */

    public void setRoleId( long roleId )
    {
        this.roleId = roleId;
    }

    public String getSubRoleName()
    {
        return this.subRoleName;
    }
   /**
    * @struts.validator type="required"
    */

    public void setSubRoleName( String subRoleName )
    {
        this.subRoleName = subRoleName;
    }

    public String getType1()
    {
        return this.type1;
    }
   /**
    * @struts.validator type="required"
    */

    public void setType1( String type1 )
    {
        this.type1 = type1;
    }

    public String getType2()
    {
        return this.type2;
    }
   /**
    * @struts.validator type="required"
    */

    public void setType2( String type2 )
    {
        this.type2 = type2;
    }

    public String getType3()
    {
        return this.type3;
    }
   /**
    * @struts.validator type="required"
    */

    public void setType3( String type3 )
    {
        this.type3 = type3;
    }

        /* To add non XDoclet-generated methods, create a file named
           xdoclet-TawSystemSubRoleForm.java 
           containing the additional code and place it in your metadata/web directory.
        */
    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     *                                                javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

}
