package com.boco.eoms.commons.system.role.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="tawSystemUserRefPostForm" 
 */
public class TawSystemUserRefPostForm
    extends    BaseForm
    implements java.io.Serializable
{

    protected String id;

    protected String postId;

    protected String userId;

    /** Default empty constructor. */
    public TawSystemUserRefPostForm() {}

    public String getId()
    {
        return this.id;
    }
   /**
    */

    public void setId( String id )
    {
        this.id = id;
    }

    public String getPostId()
    {
        return this.postId;
    }
   /**
    * @struts.validator type="required"
    */

    public void setPostId( String postId )
    {
        this.postId = postId;
    }

    public String getUserId()
    {
        return this.userId;
    }
   /**
    * @struts.validator type="required"
    */

    public void setUserId( String userId )
    {
        this.userId = userId;
    }

        /* To add non XDoclet-generated methods, create a file named
           xdoclet-TawSystemUserRefPostForm.java 
           containing the additional code and place it in your metadata/web directory.
        */
    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     *                                                javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

}
