package com.boco.eoms.commons.system.role.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with
 * XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 * 
 * @struts.form name="tawSystemPostForm"
 */
public class TawSystemRoleForm extends BaseForm implements java.io.Serializable {

	protected String deleted;

	protected String deptId;

	protected String levelId;

	protected String limitCount;

	protected String notes;

	protected long parentId;

	protected long roleId;

	protected String roleName;

	protected String roleTypeId;

	protected String singleId;

	protected String structureFlag;

	protected String titleId;

	protected String workflowFlag;

	protected Integer leaf;

	private String roletypeName = "";

	private String parentName;

	public final static int ADD = 1;

	public final static int EDIT = 2;

	private int strutsAction;

	private Long postId;

	/**
	 * @return Returns the leaf.
	 */
	public Integer getLeaf() {
		return leaf;
	}

	/**
	 * @param leaf
	 *            The leaf to set.
	 */
	public void setLeaf(Integer leaf) {
		this.leaf = leaf;
	}

	/**
	 * @return Returns the postId.
	 */
	public Long getPostId() {
		return postId;
	}

	/**
	 * @param postId
	 *            The postId to set.
	 */
	public void setPostId(Long postId) {
		this.postId = postId;
	}

	public int getStrutsAction() {
		return strutsAction;
	}

	public void setStrutsAction(int strutsAction) {
		this.strutsAction = strutsAction;
	}

	/** Default empty constructor. */
	public TawSystemRoleForm() {
	}

	public String getDeleted() {
		return this.deleted;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setDeleted(String deleted) {
		this.deleted = deleted;
	}

	public String getDeptId() {
		return this.deptId;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	public String getLevelId() {
		return this.levelId;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setLevelId(String levelId) {
		this.levelId = levelId;
	}

	public String getLimitCount() {
		return this.limitCount;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setLimitCount(String limitCount) {
		this.limitCount = limitCount;
	}

	public String getNotes() {
		return this.notes;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public long getParentId() {
		return this.parentId;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setParentId(long parentId) {
		this.parentId = parentId;
	}

	public long getRoleId() {
		return this.roleId;
	}

	/**
	 */

	public void setRoleId(long roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getRoleTypeId() {
		return this.roleTypeId;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setRoleTypeId(String roleTypeId) {
		this.roleTypeId = roleTypeId;
	}

	public String getSingleId() {
		return this.singleId;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setSingleId(String singleId) {
		this.singleId = singleId;
	}

	public String getStructureFlag() {
		return this.structureFlag;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setStructureFlag(String structureFlag) {
		this.structureFlag = structureFlag;
	}

	public String getTitleId() {
		return this.titleId;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setTitleId(String titleId) {
		this.titleId = titleId;
	}

	public String getWorkflowFlag() {
		return this.workflowFlag;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setWorkflowFlag(String workflowFlag) {
		this.workflowFlag = workflowFlag;
	}

	/*
	 * To add non XDoclet-generated methods, create a file named
	 * xdoclet-TawSystemRoleForm.java containing the additional code and place
	 * it in your metadata/web directory.
	 */
	/**
	 * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
	 *      javax.servlet.http.HttpServletRequest)
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// reset any boolean data types to false

	}

	public String getRoletypeName() {
		return roletypeName;
	}

	public void setRoletypeName(String roletypeName) {
		this.roletypeName = roletypeName;
	}

	public String getParentName() {
		return parentName;
	}

	public void setParentName(String parentName) {
		this.parentName = parentName;
	}

	private FormFile thisFile;

	public FormFile getThisFile() {
		return thisFile;
	}

	public void setThisFile(FormFile thisFile) {
		this.thisFile = thisFile;
	}
}
