package com.boco.eoms.commons.system.role.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with
 * XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 * 
 * @struts.form name="tawSystemRoleImportForm"
 */
public class TawSystemRoleImportForm extends BaseForm implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1348202870495271990L;

	protected String accessoriesId;

	protected String id;

	protected String memo;

	protected String roleId;

	protected String subRoleId;

	protected String version;

	protected String versionAt;

	public void setAccessories(String accessories) {
		this.accessoriesId = accessories;
	}

	/** Default empty constructor. */
	public TawSystemRoleImportForm() {
	}

	public String getAccessoriesId() {
		return this.accessoriesId;
	}

	/**
	 */

	public void setAccessoriesId(String accessoriesId) {
		this.accessoriesId = accessoriesId;
	}

	public String getId() {
		return this.id;
	}

	/**
	 */

	public void setId(String id) {
		this.id = id;
	}

	public String getMemo() {
		return this.memo;
	}

	/**
	 */

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getRoleId() {
		return this.roleId;
	}

	/**
	 */

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getSubRoleId() {
		return this.subRoleId;
	}

	/**
	 */

	public void setSubRoleId(String subRoleId) {
		this.subRoleId = subRoleId;
	}

	public String getVersion() {
		return this.version;
	}

	/**
	 */

	public void setVersion(String version) {
		this.version = version;
	}

	public String getVersionAt() {
		return this.versionAt;
	}

	/**
	 */

	public void setVersionAt(String versionAt) {
		this.versionAt = versionAt;
	}

	/*
	 * To add non XDoclet-generated methods, create a file named
	 * xdoclet-TawSystemRoleImportForm.java containing the additional code and
	 * place it in your metadata/web directory.
	 */
	/**
	 * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
	 *      javax.servlet.http.HttpServletRequest)
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// reset any boolean data types to false

	}

}
