package com.boco.eoms.commons.system.role.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="tawSystemOrganizationProxyForm" 
 */
public class TawSystemOrganizationProxyForm
    extends    BaseForm
    implements java.io.Serializable
{

    protected String deleted;

    protected String endTime;

    protected String fromUserId;

    protected String id;

    protected String proxyPostId;

    protected String startTime;

    protected String toUserId;

    /** Default empty constructor. */
    public TawSystemOrganizationProxyForm() {}

    public String getDeleted()
    {
        return this.deleted;
    }
   /**
    * @struts.validator type="required"
    */

    public void setDeleted( String deleted )
    {
        this.deleted = deleted;
    }

    public String getEndTime()
    {
        return this.endTime;
    }
   /**
    * @struts.validator type="required"
    */

    public void setEndTime( String endTime )
    {
        this.endTime = endTime;
    }

    public String getFromUserId()
    {
        return this.fromUserId;
    }
   /**
    * @struts.validator type="required"
    */

    public void setFromUserId( String fromUserId )
    {
        this.fromUserId = fromUserId;
    }

    public String getId()
    {
        return this.id;
    }
   /**
    */

    public void setId( String id )
    {
        this.id = id;
    }

    public String getProxyPostId()
    {
        return this.proxyPostId;
    }
   /**
    * @struts.validator type="required"
    */

    public void setProxyPostId( String proxyPostId )
    {
        this.proxyPostId = proxyPostId;
    }

    public String getStartTime()
    {
        return this.startTime;
    }
   /**
    * @struts.validator type="required"
    */

    public void setStartTime( String startTime )
    {
        this.startTime = startTime;
    }

    public String getToUserId()
    {
        return this.toUserId;
    }
   /**
    * @struts.validator type="required"
    */

    public void setToUserId( String toUserId )
    {
        this.toUserId = toUserId;
    }

        /* To add non XDoclet-generated methods, create a file named
           xdoclet-TawSystemOrganizationProxyForm.java 
           containing the additional code and place it in your metadata/web directory.
        */
    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     *                                                javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

}
