package com.boco.eoms.commons.system.role.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="tawSystemPostForm" 
 */
public class TawSystemPostForm
    extends    BaseForm
    implements java.io.Serializable
{

    protected String deleted = "0";

    protected String deptId;

    protected String levelId;

    protected String limitCount;

    protected String notes;

    protected long parentId;

    protected long postId;

    protected String postName;

    protected String postTypeId;

    protected String singleId;

    protected String structureFlag;

    protected String titleId;

    protected String workflowFlag;
    
    private String posttypeName = "";
    
    private String parentName;
    
    private String userids;
    
    private String subroleids;
    

	/**
	 * @return Returns the subroleids.
	 */
	public String getSubroleids() {
		return subroleids;
	}
	/**
	 * @param subroleids The subroleids to set.
	 */
	public void setSubroleids(String subroleids) {
		this.subroleids = subroleids;
	}
	/**
	 * @return Returns the userids.
	 */
	public String getUserids() {
		return userids;
	}
	/**
	 * @param userids The userids to set.
	 */
	public void setUserids(String userids) {
		this.userids = userids;
	}
    public final static int ADD = 1;
    public final static int EDIT = 2;
    private int strutsAction;

    public int getStrutsAction() {
		return strutsAction;
	}

	public void setStrutsAction(int strutsAction) {
		this.strutsAction = strutsAction;
	}

	/** Default empty constructor. */
    public TawSystemPostForm() {}

    public String getDeleted()
    {
        return this.deleted;
    }
   /**
    * @struts.validator type="required"
    */

    public void setDeleted( String deleted )
    {
        this.deleted = deleted;
    }

    public String getDeptId()
    {
        return this.deptId;
    }
   /**
    * @struts.validator type="required"
    */

    public void setDeptId( String deptId )
    {
        this.deptId = deptId;
    }

    public String getLevelId()
    {
        return this.levelId;
    }
   /**
    * @struts.validator type="required"
    */

    public void setLevelId( String levelId )
    {
        this.levelId = levelId;
    }

    public String getLimitCount()
    {
        return this.limitCount;
    }
   /**
    * @struts.validator type="required"
    */

    public void setLimitCount( String limitCount )
    {
        this.limitCount = limitCount;
    }

    public String getNotes()
    {
        return this.notes;
    }
   /**
    * @struts.validator type="required"
    */

    public void setNotes( String notes )
    {
        this.notes = notes;
    }

    public long getParentId()
    {
        return this.parentId;
    }
   /**
    * @struts.validator type="required"
    */

    public void setParentId( long parentId )
    {
        this.parentId = parentId;
    }

    public long getPostId()
    {
        return this.postId;
    }
   /**
    */

    public void setPostId( long postId )
    {
        this.postId = postId;
    }

    public String getPostName()
    {
        return this.postName;
    }
   /**
    * @struts.validator type="required"
    */

    public void setPostName( String postName )
    {
        this.postName = postName;
    }

    public String getPostTypeId()
    {
        return this.postTypeId;
    }
   /**
    * @struts.validator type="required"
    */

    public void setPostTypeId( String postTypeId )
    {
        this.postTypeId = postTypeId;
    }

    public String getSingleId()
    {
        return this.singleId;
    }
   /**
    * @struts.validator type="required"
    */

    public void setSingleId( String singleId )
    {
        this.singleId = singleId;
    }

    public String getStructureFlag()
    {
        return this.structureFlag;
    }
   /**
    * @struts.validator type="required"
    */

    public void setStructureFlag( String structureFlag )
    {
        this.structureFlag = structureFlag;
    }

    public String getTitleId()
    {
        return this.titleId;
    }
   /**
    * @struts.validator type="required"
    */

    public void setTitleId( String titleId )
    {
        this.titleId = titleId;
    }

    public String getWorkflowFlag()
    {
        return this.workflowFlag;
    }
   /**
    * @struts.validator type="required"
    */

    public void setWorkflowFlag( String workflowFlag )
    {
        this.workflowFlag = workflowFlag;
    }

        /* To add non XDoclet-generated methods, create a file named
           xdoclet-TawSystemPostForm.java 
           containing the additional code and place it in your metadata/web directory.
        */
    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     *                                                javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

	public String getPosttypeName() {
		return posttypeName;
	}

	public void setPosttypeName(String posttypeName) {
		this.posttypeName = posttypeName;
	}

	public String getParentName() {
		return parentName;
	}

	public void setParentName(String parentName) {
		this.parentName = parentName;
	}

}
