package com.boco.eoms.commons.accessories.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with
 * XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 * 
 * @struts.form name="tawCommonsAccessoriesConfigForm"
 */
public class TawCommonsAccessoriesConfigForm extends BaseForm implements
		java.io.Serializable {
	/**
	 * 文件允许存放类型
	 */
	protected String[] allowFileType; 
	/**
	 * 应用模板编码
	 */
	protected String appCode;
	/**
	 * 应用模板名称
	 */
	protected String appName;
	/**
	 * 允许存放的最大size
	 */
	protected String maxSize;
	/**
	 * 文件存放路径
	 */
	protected String path;
	/**
	 *  应用模板ID
	 */
	protected String appId;
	
	protected String id;

	/**
	 * @return Returns the id.
	 */
	public String getId() {
		return id;
	}
	/**
	 * @param id The id to set.
	 */
	public void setId(String id) {
		this.id = id;
	}
	/**
	 * @return Returns the appId.
	 */
	public String getAppId() {
		return appId;
	}
	/**
	 * @param appId The appId to set.
	 */
	public void setAppId(String appId) {
		this.appId = appId;
	}
	/** Default empty constructor. */
	public TawCommonsAccessoriesConfigForm() {
	}

	public String[] getAllowFileType() {
		return this.allowFileType;
	}

	/**
	 */

	public void setAllowFileType(String[] allowFileType) {
		this.allowFileType = allowFileType;
	}

	public String getAppCode() {
		return this.appCode;
	}

	/**
	 */

	public void setAppCode(String appCode) {
		this.appCode = appCode;
	}

	public String getAppName() {
		return this.appName;
	}

	/**
	 */

	public void setAppName(String appName) {
		this.appName = appName;
	}

	public String getMaxSize() {
		return this.maxSize;
	}

	/**
	 */

	public void setMaxSize(String maxSize) {
		this.maxSize = maxSize;
	}

	public String getPath() {
		return this.path;
	}

	/**
	 */

	public void setPath(String path) {
		this.path = path;
	}

	/*
	 * To add non XDoclet-generated methods, create a file named
	 * xdoclet-TawCommonsAccessoriesConfigForm.java containing the additional
	 * code and place it in your metadata/web directory.
	 */
	/**
	 * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
	 *      javax.servlet.http.HttpServletRequest)
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// reset any boolean data types to false

	}

}
