package com.boco.eoms.commons.message.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with
 * XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 * 
 * @struts.form name="tawCommonMessageModelTypeForm"
 */
public class TawCommonMessageModelTypeForm extends BaseForm implements
		java.io.Serializable {

	private static final long serialVersionUID = 1L;

	protected String id;

	protected String modelid;

	protected String modelname;

	protected String modelremark;

	protected String userid;

	public String getUserid() {
		return userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	/** Default empty constructor. */
	public TawCommonMessageModelTypeForm() {
	}

	public String getId() {
		return this.id;
	}

	/**
	 */

	public void setId(String id) {
		this.id = id;
	}

	public String getModelid() {
		return this.modelid;
	}

	/**
	 */

	public void setModelid(String modelid) {
		this.modelid = modelid;
	}

	public String getModelname() {
		return this.modelname;
	}

	/**
	 */

	public void setModelname(String modelname) {
		this.modelname = modelname;
	}

	public String getModelremark() {
		return this.modelremark;
	}

	/**
	 */

	public void setModelremark(String modelremark) {
		this.modelremark = modelremark;
	}

	/*
	 * To add non XDoclet-generated methods, create a file named
	 * xdoclet-TawCommonMessageModelTypeForm.java containing the additional code
	 * and place it in your metadata/web directory.
	 */
	/**
	 * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
	 *      javax.servlet.http.HttpServletRequest)
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// reset any boolean data types to false

	}

}
