package com.boco.eoms.commons.message.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with
 * XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 * 
 * @struts.form name="tawCommonMessageMonitorRefForm"
 */
public class TawCommonMessageMonitorRefForm extends BaseForm implements
		java.io.Serializable {

	private static final long serialVersionUID = 1L;

	protected String id;

	protected String monitorid;

	protected String teloremail;

	protected String toobjectid;

	protected String userid;

	/** Default empty constructor. */
	public TawCommonMessageMonitorRefForm() {
	}

	public String getId() {
		return this.id;
	}

	/**
	 */

	public void setId(String id) {
		this.id = id;
	}

	public String getMonitorid() {
		return this.monitorid;
	}

	/**
	 */

	public void setMonitorid(String monitorid) {
		this.monitorid = monitorid;
	}

	public String getTeloremail() {
		return this.teloremail;
	}

	/**
	 */

	public void setTeloremail(String teloremail) {
		this.teloremail = teloremail;
	}

	public String getToobjectid() {
		return this.toobjectid;
	}

	/**
	 */

	public void setToobjectid(String toobjectid) {
		this.toobjectid = toobjectid;
	}

	public String getUserid() {
		return this.userid;
	}

	/**
	 */

	public void setUserid(String userid) {
		this.userid = userid;
	}

	/*
	 * To add non XDoclet-generated methods, create a file named
	 * xdoclet-TawCommonMessageMonitorRefForm.java containing the additional
	 * code and place it in your metadata/web directory.
	 */
	/**
	 * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
	 *      javax.servlet.http.HttpServletRequest)
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// reset any boolean data types to false

	}

}
