package com.boco.eoms.commons.message.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with
 * XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 * 
 * @struts.form name="tawCommonMessageOpertypeForm"
 */
public class TawCommonMessageOpertypeForm extends BaseForm implements
		java.io.Serializable {

	private static final long serialVersionUID = 1L;

	protected String id;

	protected String modelid;

	protected String modelname;

	protected String operid;

	protected String opername;

	protected String operremark;

	protected String operrefmodelid;

	protected String userid;

	public String getOperrefmodelid() {
		return operrefmodelid;
	}

	public void setOperrefmodelid(String operrefmodelid) {
		this.operrefmodelid = operrefmodelid;
	}

	public String getUserid() {
		return userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	/** Default empty constructor. */
	public TawCommonMessageOpertypeForm() {
	}

	public String getId() {
		return this.id;
	}

	/**
	 */

	public void setId(String id) {
		this.id = id;
	}

	public String getModelid() {
		return this.modelid;
	}

	/**
	 */

	public void setModelid(String modelid) {
		this.modelid = modelid;
	}

	public String getModelname() {
		return this.modelname;
	}

	/**
	 */

	public void setModelname(String modelname) {
		this.modelname = modelname;
	}

	public String getOperid() {
		return this.operid;
	}

	/**
	 */

	public void setOperid(String operid) {
		this.operid = operid;
	}

	public String getOpername() {
		return this.opername;
	}

	/**
	 */

	public void setOpername(String opername) {
		this.opername = opername;
	}

	public String getOperremark() {
		return this.operremark;
	}

	/**
	 */

	public void setOperremark(String operremark) {
		this.operremark = operremark;
	}

	/*
	 * To add non XDoclet-generated methods, create a file named
	 * xdoclet-TawCommonMessageOpertypeForm.java containing the additional code
	 * and place it in your metadata/web directory.
	 */
	/**
	 * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
	 *      javax.servlet.http.HttpServletRequest)
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// reset any boolean data types to false

	}

}
