package com.boco.eoms.commons.message.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with
 * XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 * 
 * @struts.form name="tawCommonMessageSubscribeForm"
 */
public class TawCommonMessageSubscribeForm extends BaseForm implements
		java.io.Serializable {

	private static final long serialVersionUID = 1L;

	protected String endday;

	protected String endhour;

	protected String endmin;

	protected String messageid;

	protected String receivertype;

	protected String remark;

	protected String remarktwo;

	protected String revecer;

	protected String sendcount;

	protected String startday;

	protected String starthour;

	protected String startmin;

	protected String userid;

	protected String id;

	protected String sendcuttime;

	/** Default empty constructor. */
	public TawCommonMessageSubscribeForm() {
	}

	public String getEndday() {
		return this.endday;
	}

	/**
	 */

	public void setEndday(String endday) {
		this.endday = endday;
	}

	public String getEndhour() {
		return this.endhour;
	}

	/**
	 */

	public void setEndhour(String endhour) {
		this.endhour = endhour;
	}

	public String getEndmin() {
		return this.endmin;
	}

	/**
	 */

	public void setEndmin(String endmin) {
		this.endmin = endmin;
	}

	public String getMessageid() {
		return this.messageid;
	}

	/**
	 */

	public void setMessageid(String messageid) {
		this.messageid = messageid;
	}

	public String getReceivertype() {
		return this.receivertype;
	}

	/**
	 */

	public void setReceivertype(String receivertype) {
		this.receivertype = receivertype;
	}

	public String getRemark() {
		return this.remark;
	}

	/**
	 */

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getRemarktwo() {
		return this.remarktwo;
	}

	/**
	 */

	public void setRemarktwo(String remarktwo) {
		this.remarktwo = remarktwo;
	}

	public String getRevecer() {
		return this.revecer;
	}

	/**
	 */

	public void setRevecer(String revecer) {
		this.revecer = revecer;
	}

	public String getSendcount() {
		return this.sendcount;
	}

	/**
	 */

	public void setSendcount(String sendcount) {
		this.sendcount = sendcount;
	}

	public String getStartday() {
		return this.startday;
	}

	/**
	 */

	public void setStartday(String startday) {
		this.startday = startday;
	}

	public String getStarthour() {
		return this.starthour;
	}

	/**
	 */

	public void setStarthour(String starthour) {
		this.starthour = starthour;
	}

	public String getStartmin() {
		return this.startmin;
	}

	/**
	 */

	public void setStartmin(String startmin) {
		this.startmin = startmin;
	}

	public String getUserid() {
		return this.userid;
	}

	/**
	 */

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getId() {
		return this.id;
	}

	/**
	 */

	public void setId(String id) {
		this.id = id;
	}

	public String getSendcuttime() {
		return this.sendcuttime;
	}

	/**
	 */

	public void setSendcuttime(String sendcuttime) {
		this.sendcuttime = sendcuttime;
	}

	/*
	 * To add non XDoclet-generated methods, create a file named
	 * xdoclet-TawCommonMessageSubscribeForm.java containing the additional code
	 * and place it in your metadata/web directory.
	 */
	/**
	 * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
	 *      javax.servlet.http.HttpServletRequest)
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// reset any boolean data types to false

	}

}
