package com.boco.eoms.sheet.modifytime.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="modifyTimeForm" 
 */
public class ModifyTimeForm
    extends    BaseForm
    implements java.io.Serializable
{

    protected String id;

    protected String beginTime;

    protected String endTime;

    protected String functionary;

    protected String introduction;

    protected String local;

    protected String metNet;

    protected String specialtyOne;
    
    protected String specialtyTwo;
    
    protected String specialtyThree;

    protected String title;

    protected String type;

    protected String remarks;

    protected String deleted;

    /** Default empty constructor. */
    public ModifyTimeForm() {}

    public String getId()
    {
        return this.id;
    }
   /**
    */

    public void setId( String id )
    {
        this.id = id;
    }

    public String getBeginTime()
    {
        return this.beginTime;
    }
   /**
    * @struts.validator type="required"
    */

    public void setBeginTime( String beginTime )
    {
        this.beginTime = beginTime;
    }

    public String getEndTime()
    {
        return this.endTime;
    }
   /**
    * @struts.validator type="required"
    */

    public void setEndTime( String endTime )
    {
        this.endTime = endTime;
    }

    public String getFunctionary()
    {
        return this.functionary;
    }
   /**
    * @struts.validator type="required"
    */

    public void setFunctionary( String functionary )
    {
        this.functionary = functionary;
    }

    public String getIntroduction()
    {
        return this.introduction;
    }
   /**
    * @struts.validator type="required"
    */

    public void setIntroduction( String introduction )
    {
        this.introduction = introduction;
    }

    public String getLocal()
    {
        return this.local;
    }
   /**
    * @struts.validator type="required"
    */

    public void setLocal( String local )
    {
        this.local = local;
    }

    public String getMetNet()
    {
        return this.metNet;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMetNet( String metNet )
    {
        this.metNet = metNet;
    }

	public String getSpecialtyOne() {
		return specialtyOne;
	}

	public void setSpecialtyOne(String specialtyOne) {
		this.specialtyOne = specialtyOne;
	}
    
	public String getSpecialtyTwo() {
		return specialtyTwo;
	}

	public void setSpecialtyTwo(String specialtyTwo) {
		this.specialtyTwo = specialtyTwo;
	}
    
	public String getSpecialtyThree() {
		return specialtyThree;
	}

	public void setSpecialtyThree(String specialtyThree) {
		this.specialtyThree = specialtyThree;
	}

    public String getTitle()
    {
        return this.title;
    }
   /**
    * @struts.validator type="required"
    */

    public void setTitle( String title )
    {
        this.title = title;
    }

    public String getType()
    {
        return this.type;
    }
   /**
    * @struts.validator type="required"
    */

    public void setType( String type )
    {
        this.type = type;
    }

    public String getRemarks()
    {
        return this.remarks;
    }
   /**
    * @struts.validator type="required"
    */

    public void setRemarks( String remarks )
    {
        this.remarks = remarks;
    }

    public String getDeleted()
    {
        return this.deleted;
    }
   /**
    * @struts.validator type="required"
    */

    public void setDeleted( String deleted )
    {
        this.deleted = deleted;
    }

        /* To add non XDoclet-generated methods, create a file named
           xdoclet-ModifyTimeForm.java 
           containing the additional code and place it in your metadata/web directory.
        */
    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     *                                                javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

}
