package com.boco.eoms.parter.baseinfo.lanmetermgr.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="lanmetermgrForm" 
 */
public class LanmetermgrForm
    extends    BaseForm
    implements java.io.Serializable
{

    protected String id;

    protected String maintenUnitId;

    protected String maintenUnitIdCou;

    protected String maintenUnitIdRem;

    protected String OTDR;

    protected String OTDRCou;

    protected String OTDRRem;

    protected String lighCableFinder;

    protected String lighCableFinderCou;

    protected String lighCableFinderRem;

    protected String groundFinder;

    protected String groundFinderCou;

    protected String groundFinderRem;

    protected String portableGPS;

    protected String portableGPSCou;

    protected String portableGPSRem;

    protected String autoFiberWeld;

    protected String autoFiberWeldCou;

    protected String autoFiberWeldRem;

    protected String fiberStrip;

    protected String fiberStripCou;

    protected String fiberStripRem;

    protected String losetubeStrip;

    protected String losetubeStripCou;

    protected String losetubeStripRem;

    protected String pspStrip;

    protected String pspStripCou;

    protected String pspStripRem;

    protected String lighCableReame;

    protected String lighCableReameCou;

    protected String lighCableReameRem;

    protected String beamTubeFinde;

    protected String beamTubeFindeCou;

    protected String beamTubeFindeRem;

    protected String fiberAmputat;

    protected String fiberAmputatCou;

    protected String fiberAmputatRem;

    protected String VLinker;

    protected String VLinkerCou;

    protected String VLinkerRem;

    protected String scavPump;

    protected String scavPumpCou;

    protected String scavPumpRem;

    protected String fiberRecognizer;

    protected String fiberRecognizerCou;

    protected String fiberRecognizerRem;

    protected String mechSpecTool;

    protected String mechSpecToolCou;

    protected String mechSpecToolRem;

    protected String dynamo;

    protected String dynamoCou;

    protected String dynamoRem;

    protected String mainterCar;

    protected String mainterCarCou;

    protected String mainterCarRem;

    protected String waterPump;

    protected String waterPumpCou;

    protected String waterPumpRem;

    protected String mobileGps;

    protected String mobileGpsCou;

    protected String mobileGpsRem;

    /** Default empty constructor. */
    public LanmetermgrForm() {}

    public String getId()
    {
        return this.id;
    }
   /**
    */

    public void setId( String id )
    {
        this.id = id;
    }

    public String getMaintenUnitId()
    {
        return this.maintenUnitId;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMaintenUnitId( String maintenUnitId )
    {
        this.maintenUnitId = maintenUnitId;
    }

    public String getMaintenUnitIdCou()
    {
        return this.maintenUnitIdCou;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMaintenUnitIdCou( String maintenUnitIdCou )
    {
        this.maintenUnitIdCou = maintenUnitIdCou;
    }

    public String getMaintenUnitIdRem()
    {
        return this.maintenUnitIdRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMaintenUnitIdRem( String maintenUnitIdRem )
    {
        this.maintenUnitIdRem = maintenUnitIdRem;
    }

    public String getOTDR()
    {
        return this.OTDR;
    }
   /**
    * @struts.validator type="required"
    */

    public void setOTDR( String OTDR )
    {
        this.OTDR = OTDR;
    }

    public String getOTDRCou()
    {
        return this.OTDRCou;
    }
   /**
    * @struts.validator type="required"
    */

    public void setOTDRCou( String OTDRCou )
    {
        this.OTDRCou = OTDRCou;
    }

    public String getOTDRRem()
    {
        return this.OTDRRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setOTDRRem( String OTDRRem )
    {
        this.OTDRRem = OTDRRem;
    }

    public String getLighCableFinder()
    {
        return this.lighCableFinder;
    }
   /**
    * @struts.validator type="required"
    */

    public void setLighCableFinder( String lighCableFinder )
    {
        this.lighCableFinder = lighCableFinder;
    }

    public String getLighCableFinderCou()
    {
        return this.lighCableFinderCou;
    }
   /**
    * @struts.validator type="required"
    */

    public void setLighCableFinderCou( String lighCableFinderCou )
    {
        this.lighCableFinderCou = lighCableFinderCou;
    }

    public String getLighCableFinderRem()
    {
        return this.lighCableFinderRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setLighCableFinderRem( String lighCableFinderRem )
    {
        this.lighCableFinderRem = lighCableFinderRem;
    }

    public String getGroundFinder()
    {
        return this.groundFinder;
    }
   /**
    * @struts.validator type="required"
    */

    public void setGroundFinder( String groundFinder )
    {
        this.groundFinder = groundFinder;
    }

    public String getGroundFinderCou()
    {
        return this.groundFinderCou;
    }
   /**
    * @struts.validator type="required"
    */

    public void setGroundFinderCou( String groundFinderCou )
    {
        this.groundFinderCou = groundFinderCou;
    }

    public String getGroundFinderRem()
    {
        return this.groundFinderRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setGroundFinderRem( String groundFinderRem )
    {
        this.groundFinderRem = groundFinderRem;
    }

    public String getPortableGPS()
    {
        return this.portableGPS;
    }
   /**
    * @struts.validator type="required"
    */

    public void setPortableGPS( String portableGPS )
    {
        this.portableGPS = portableGPS;
    }

    public String getPortableGPSCou()
    {
        return this.portableGPSCou;
    }
   /**
    * @struts.validator type="required"
    */

    public void setPortableGPSCou( String portableGPSCou )
    {
        this.portableGPSCou = portableGPSCou;
    }

    public String getPortableGPSRem()
    {
        return this.portableGPSRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setPortableGPSRem( String portableGPSRem )
    {
        this.portableGPSRem = portableGPSRem;
    }

    public String getAutoFiberWeld()
    {
        return this.autoFiberWeld;
    }
   /**
    * @struts.validator type="required"
    */

    public void setAutoFiberWeld( String autoFiberWeld )
    {
        this.autoFiberWeld = autoFiberWeld;
    }

    public String getAutoFiberWeldCou()
    {
        return this.autoFiberWeldCou;
    }
   /**
    * @struts.validator type="required"
    */

    public void setAutoFiberWeldCou( String autoFiberWeldCou )
    {
        this.autoFiberWeldCou = autoFiberWeldCou;
    }

    public String getAutoFiberWeldRem()
    {
        return this.autoFiberWeldRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setAutoFiberWeldRem( String autoFiberWeldRem )
    {
        this.autoFiberWeldRem = autoFiberWeldRem;
    }

    public String getFiberStrip()
    {
        return this.fiberStrip;
    }
   /**
    * @struts.validator type="required"
    */

    public void setFiberStrip( String fiberStrip )
    {
        this.fiberStrip = fiberStrip;
    }

    public String getFiberStripCou()
    {
        return this.fiberStripCou;
    }
   /**
    * @struts.validator type="required"
    */

    public void setFiberStripCou( String fiberStripCou )
    {
        this.fiberStripCou = fiberStripCou;
    }

    public String getFiberStripRem()
    {
        return this.fiberStripRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setFiberStripRem( String fiberStripRem )
    {
        this.fiberStripRem = fiberStripRem;
    }

    public String getLosetubeStrip()
    {
        return this.losetubeStrip;
    }
   /**
    * @struts.validator type="required"
    */

    public void setLosetubeStrip( String losetubeStrip )
    {
        this.losetubeStrip = losetubeStrip;
    }

    public String getLosetubeStripCou()
    {
        return this.losetubeStripCou;
    }
   /**
    * @struts.validator type="required"
    */

    public void setLosetubeStripCou( String losetubeStripCou )
    {
        this.losetubeStripCou = losetubeStripCou;
    }

    public String getLosetubeStripRem()
    {
        return this.losetubeStripRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setLosetubeStripRem( String losetubeStripRem )
    {
        this.losetubeStripRem = losetubeStripRem;
    }

    public String getPspStrip()
    {
        return this.pspStrip;
    }
   /**
    * @struts.validator type="required"
    */

    public void setPspStrip( String pspStrip )
    {
        this.pspStrip = pspStrip;
    }

    public String getPspStripCou()
    {
        return this.pspStripCou;
    }
   /**
    * @struts.validator type="required"
    */

    public void setPspStripCou( String pspStripCou )
    {
        this.pspStripCou = pspStripCou;
    }

    public String getPspStripRem()
    {
        return this.pspStripRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setPspStripRem( String pspStripRem )
    {
        this.pspStripRem = pspStripRem;
    }

    public String getLighCableReame()
    {
        return this.lighCableReame;
    }
   /**
    * @struts.validator type="required"
    */

    public void setLighCableReame( String lighCableReame )
    {
        this.lighCableReame = lighCableReame;
    }

    public String getLighCableReameCou()
    {
        return this.lighCableReameCou;
    }
   /**
    * @struts.validator type="required"
    */

    public void setLighCableReameCou( String lighCableReameCou )
    {
        this.lighCableReameCou = lighCableReameCou;
    }

    public String getLighCableReameRem()
    {
        return this.lighCableReameRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setLighCableReameRem( String lighCableReameRem )
    {
        this.lighCableReameRem = lighCableReameRem;
    }

    public String getBeamTubeFinde()
    {
        return this.beamTubeFinde;
    }
   /**
    * @struts.validator type="required"
    */

    public void setBeamTubeFinde( String beamTubeFinde )
    {
        this.beamTubeFinde = beamTubeFinde;
    }

    public String getBeamTubeFindeCou()
    {
        return this.beamTubeFindeCou;
    }
   /**
    * @struts.validator type="required"
    */

    public void setBeamTubeFindeCou( String beamTubeFindeCou )
    {
        this.beamTubeFindeCou = beamTubeFindeCou;
    }

    public String getBeamTubeFindeRem()
    {
        return this.beamTubeFindeRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setBeamTubeFindeRem( String beamTubeFindeRem )
    {
        this.beamTubeFindeRem = beamTubeFindeRem;
    }

    public String getFiberAmputat()
    {
        return this.fiberAmputat;
    }
   /**
    * @struts.validator type="required"
    */

    public void setFiberAmputat( String fiberAmputat )
    {
        this.fiberAmputat = fiberAmputat;
    }

    public String getFiberAmputatCou()
    {
        return this.fiberAmputatCou;
    }
   /**
    * @struts.validator type="required"
    */

    public void setFiberAmputatCou( String fiberAmputatCou )
    {
        this.fiberAmputatCou = fiberAmputatCou;
    }

    public String getFiberAmputatRem()
    {
        return this.fiberAmputatRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setFiberAmputatRem( String fiberAmputatRem )
    {
        this.fiberAmputatRem = fiberAmputatRem;
    }

    public String getVLinker()
    {
        return this.VLinker;
    }
   /**
    * @struts.validator type="required"
    */

    public void setVLinker( String VLinker )
    {
        this.VLinker = VLinker;
    }

    public String getVLinkerCou()
    {
        return this.VLinkerCou;
    }
   /**
    * @struts.validator type="required"
    */

    public void setVLinkerCou( String VLinkerCou )
    {
        this.VLinkerCou = VLinkerCou;
    }

    public String getVLinkerRem()
    {
        return this.VLinkerRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setVLinkerRem( String VLinkerRem )
    {
        this.VLinkerRem = VLinkerRem;
    }

    public String getScavPump()
    {
        return this.scavPump;
    }
   /**
    * @struts.validator type="required"
    */

    public void setScavPump( String scavPump )
    {
        this.scavPump = scavPump;
    }

    public String getScavPumpCou()
    {
        return this.scavPumpCou;
    }
   /**
    * @struts.validator type="required"
    */

    public void setScavPumpCou( String scavPumpCou )
    {
        this.scavPumpCou = scavPumpCou;
    }

    public String getScavPumpRem()
    {
        return this.scavPumpRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setScavPumpRem( String scavPumpRem )
    {
        this.scavPumpRem = scavPumpRem;
    }

    public String getFiberRecognizer()
    {
        return this.fiberRecognizer;
    }
   /**
    * @struts.validator type="required"
    */

    public void setFiberRecognizer( String fiberRecognizer )
    {
        this.fiberRecognizer = fiberRecognizer;
    }

    public String getFiberRecognizerCou()
    {
        return this.fiberRecognizerCou;
    }
   /**
    * @struts.validator type="required"
    */

    public void setFiberRecognizerCou( String fiberRecognizerCou )
    {
        this.fiberRecognizerCou = fiberRecognizerCou;
    }

    public String getFiberRecognizerRem()
    {
        return this.fiberRecognizerRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setFiberRecognizerRem( String fiberRecognizerRem )
    {
        this.fiberRecognizerRem = fiberRecognizerRem;
    }

    public String getMechSpecTool()
    {
        return this.mechSpecTool;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMechSpecTool( String mechSpecTool )
    {
        this.mechSpecTool = mechSpecTool;
    }

    public String getMechSpecToolCou()
    {
        return this.mechSpecToolCou;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMechSpecToolCou( String mechSpecToolCou )
    {
        this.mechSpecToolCou = mechSpecToolCou;
    }

    public String getMechSpecToolRem()
    {
        return this.mechSpecToolRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMechSpecToolRem( String mechSpecToolRem )
    {
        this.mechSpecToolRem = mechSpecToolRem;
    }

    public String getDynamo()
    {
        return this.dynamo;
    }
   /**
    * @struts.validator type="required"
    */

    public void setDynamo( String dynamo )
    {
        this.dynamo = dynamo;
    }

    public String getDynamoCou()
    {
        return this.dynamoCou;
    }
   /**
    * @struts.validator type="required"
    */

    public void setDynamoCou( String dynamoCou )
    {
        this.dynamoCou = dynamoCou;
    }

    public String getDynamoRem()
    {
        return this.dynamoRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setDynamoRem( String dynamoRem )
    {
        this.dynamoRem = dynamoRem;
    }

    public String getMainterCar()
    {
        return this.mainterCar;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMainterCar( String mainterCar )
    {
        this.mainterCar = mainterCar;
    }

    public String getMainterCarCou()
    {
        return this.mainterCarCou;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMainterCarCou( String mainterCarCou )
    {
        this.mainterCarCou = mainterCarCou;
    }

    public String getMainterCarRem()
    {
        return this.mainterCarRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMainterCarRem( String mainterCarRem )
    {
        this.mainterCarRem = mainterCarRem;
    }

    public String getWaterPump()
    {
        return this.waterPump;
    }
   /**
    * @struts.validator type="required"
    */

    public void setWaterPump( String waterPump )
    {
        this.waterPump = waterPump;
    }

    public String getWaterPumpCou()
    {
        return this.waterPumpCou;
    }
   /**
    * @struts.validator type="required"
    */

    public void setWaterPumpCou( String waterPumpCou )
    {
        this.waterPumpCou = waterPumpCou;
    }

    public String getWaterPumpRem()
    {
        return this.waterPumpRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setWaterPumpRem( String waterPumpRem )
    {
        this.waterPumpRem = waterPumpRem;
    }

    public String getMobileGps()
    {
        return this.mobileGps;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMobileGps( String mobileGps )
    {
        this.mobileGps = mobileGps;
    }

    public String getMobileGpsCou()
    {
        return this.mobileGpsCou;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMobileGpsCou( String mobileGpsCou )
    {
        this.mobileGpsCou = mobileGpsCou;
    }

    public String getMobileGpsRem()
    {
        return this.mobileGpsRem;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMobileGpsRem( String mobileGpsRem )
    {
        this.mobileGpsRem = mobileGpsRem;
    }

        /* To add non XDoclet-generated methods, create a file named
           xdoclet-LanmetermgrForm.java 
           containing the additional code and place it in your metadata/web directory.
        */
    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     *                                                javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

}
