package com.boco.eoms.commons.interfaceMonitoring.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with
 * XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 * 
 * @struts.form name="tawSupplierkpiInfoForm"
 */
public class InterfaceConfigurationForm extends BaseForm implements
		java.io.Serializable {


	
	/**
	 * 
	 */
	private String id;
	private String interfaceName;
	private String interfaceUrl;
	private String updatedTime;
	private String shortTitle;
	private String description;
	private String provider;
	private String  direction;

	/**
	 * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
	 *      javax.servlet.http.HttpServletRequest)
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// reset any boolean data types to false

	}




	

	public String getProvider() {
		return provider;
	}


	public void setProvider(String provider) {
		this.provider = provider;
	}






	public String getId() {
		return id;
	}






	public void setId(String id) {
		this.id = id;
	}






	public String getInterfaceName() {
		return interfaceName;
	}






	public void setInterfaceName(String interfaceName) {
		this.interfaceName = interfaceName;
	}






	public String getInterfaceUrl() {
		return interfaceUrl;
	}






	public void setInterfaceUrl(String interfaceUrl) {
		this.interfaceUrl = interfaceUrl;
	}






	public String getUpdatedTime() {
		return updatedTime;
	}






	public void setUpdatedTime(String updatedTime) {
		this.updatedTime = updatedTime;
	}






	public String getShortTitle() {
		return shortTitle;
	}






	public void setShortTitle(String shortTitle) {
		this.shortTitle = shortTitle;
	}






	public String getDescription() {
		return description;
	}






	public void setDescription(String description) {
		this.description = description;
	}






	public String getDirection() {
		return direction;
	}






	public void setDirection(String direction) {
		this.direction = direction;
	}


	

}
