package com.boco.eoms.commons.interfaceMonitoring.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with
 * XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 * 
 * @struts.form name="tawSupplierkpiInfoForm"
 */
public class InterfaceMonitoringForm extends BaseForm implements
		java.io.Serializable {


	
	private String callingStartTime;
	private String callingEndTime;
	private String callingSide;
	private String provider;
	private String interFaceType;
	private String interFaceMethod;
	private String success;
	private String startTime;
	private String endTime;
	private String callDirection;
	private String interfaceName;
	private String interfaceUrl;
	private String updatedTime;
	private String shortTitle;
	private String description;
//	private String provider;
	private String  direction;
	private String deleted;
	private String moduleName ;
	private String moduleDesignation;
	private String id;
	private String  moduleid;

	/**
	 * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
	 *      javax.servlet.http.HttpServletRequest)
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// reset any boolean data types to false

	}




	public String getCallingSide() {
		return callingSide;
	}


	public void setCallingSide(String callingSide) {
		this.callingSide = callingSide;
	}


	public String getProvider() {
		return provider;
	}


	public void setProvider(String provider) {
		this.provider = provider;
	}


	public String getInterFaceType() {
		return interFaceType;
	}


	public void setInterFaceType(String interFaceType) {
		this.interFaceType = interFaceType;
	}


	public String getInterFaceMethod() {
		return interFaceMethod;
	}


	public void setInterFaceMethod(String interFaceMethod) {
		this.interFaceMethod = interFaceMethod;
	}


	public String getSuccess() {
		return success;
	}


	public void setSuccess(String success) {
		this.success = success;
	}




	public String getCallingStartTime() {
		return callingStartTime;
	}




	public void setCallingStartTime(String callingStartTime) {
		this.callingStartTime = callingStartTime;
	}




	public String getCallingEndTime() {
		return callingEndTime;
	}




	public void setCallingEndTime(String callingEndTime) {
		this.callingEndTime = callingEndTime;
	}




	public String getStartTime() {
		return startTime;
	}




	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}




	public String getEndTime() {
		return endTime;
	}




	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}




	public String getCallDirection() {
		return callDirection;
	}




	public void setCallDirection(String callDirection) {
		this.callDirection = callDirection;
	}




	public String getInterfaceName() {
		return interfaceName;
	}




	public void setInterfaceName(String interfaceName) {
		this.interfaceName = interfaceName;
	}




	public String getInterfaceUrl() {
		return interfaceUrl;
	}




	public void setInterfaceUrl(String interfaceUrl) {
		this.interfaceUrl = interfaceUrl;
	}




	public String getUpdatedTime() {
		return updatedTime;
	}




	public void setUpdatedTime(String updatedTime) {
		this.updatedTime = updatedTime;
	}




	public String getShortTitle() {
		return shortTitle;
	}




	public void setShortTitle(String shortTitle) {
		this.shortTitle = shortTitle;
	}




	public String getDescription() {
		return description;
	}




	public void setDescription(String description) {
		this.description = description;
	}




	public String getDirection() {
		return direction;
	}




	public void setDirection(String direction) {
		this.direction = direction;
	}




	public String getDeleted() {
		return deleted;
	}




	public void setDeleted(String deleted) {
		this.deleted = deleted;
	}




	public String getModuleName() {
		return moduleName;
	}




	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}




	public String getModuleDesignation() {
		return moduleDesignation;
	}




	public void setModuleDesignation(String moduleDesignation) {
		this.moduleDesignation = moduleDesignation;
	}




	public String getId() {
		return id;
	}




	public void setId(String id) {
		this.id = id;
	}




	public String getModuleid() {
		return moduleid;
	}




	public void setModuleid(String moduleid) {
		this.moduleid = moduleid;
	}

}
