package com.boco.eoms.commons.demo.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;

import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with
 * XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 * 
 * @struts.form name="tawDemoTableForm"
 */
public class TawDemoTableForm extends BaseForm implements java.io.Serializable {

	protected String authorities;

	protected String password;

	protected String username;

	protected boolean accountNonExpired;

	protected boolean accountNonLocked;

	protected boolean credentialsNonExpired;

	protected boolean enabled;

	protected String addr;

	protected String id;

	protected String tel;

	/** Default empty constructor. */
	public TawDemoTableForm() {
	}

	public String getAuthorities() {
		return this.authorities;
	}

	/**
	 */

	public void setAuthorities(String authorities) {
		this.authorities = authorities;
	}

	public String getPassword() {
		return this.password;
	}

	/**
	 */

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUsername() {
		return this.username;
	}

	/**
	 */

	public void setUsername(String username) {
		this.username = username;
	}

	public boolean isAccountNonExpired() {
		return this.accountNonExpired;
	}

	/**
	 */

	public void setAccountNonExpired(boolean accountNonExpired) {
		this.accountNonExpired = accountNonExpired;
	}

	public boolean isAccountNonLocked() {
		return this.accountNonLocked;
	}

	/**
	 */

	public void setAccountNonLocked(boolean accountNonLocked) {
		this.accountNonLocked = accountNonLocked;
	}

	public boolean isCredentialsNonExpired() {
		return this.credentialsNonExpired;
	}

	/**
	 */

	public void setCredentialsNonExpired(boolean credentialsNonExpired) {
		this.credentialsNonExpired = credentialsNonExpired;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	/**
	 */

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public String getAddr() {
		return this.addr;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setAddr(String addr) {
		this.addr = addr;
	}

	public String getId() {
		return this.id;
	}

	/**
	 */

	public void setId(String id) {
		this.id = id;
	}

	public String getTel() {
		return this.tel;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setTel(String tel) {
		this.tel = tel;
	}

	/*
	 * To add non XDoclet-generated methods, create a file named
	 * xdoclet-TawDemoTableForm.java containing the additional code and place it
	 * in your metadata/web directory.
	 */
	/**
	 * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
	 *      javax.servlet.http.HttpServletRequest)
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// reset any boolean data types to false

		this.accountNonExpired = false;

		this.accountNonLocked = false;

		this.credentialsNonExpired = false;

		this.enabled = false;

	}

}
