package com.boco.eoms.commons.system.user.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with
 * XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 * 
 * @struts.form name="tawSystemUserRefRoleForm"
 */
public class TawSystemUserRefRoleForm extends BaseForm implements
		java.io.Serializable {

	protected String id;

	protected String roleid;

	protected String status;

	private String currentsheetcount;

	protected String userid;

	protected String orgid;

	protected String remark;

	/** Default empty constructor. */
	public TawSystemUserRefRoleForm() {
	}

	public String getId() {
		return this.id;
	}

	/**
	 */

	public void setId(String id) {
		this.id = id;
	}

	public String getRoleid() {
		return this.roleid;
	}

	/**
	 */

	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}

	public String getUserid() {
		return this.userid;
	}

	/**
	 */

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getCurrentsheetcount() {
		return currentsheetcount;
	}

	public void setCurrentsheetcount(String currentsheetcount) {
		this.currentsheetcount = currentsheetcount;
	}

	public String getOrgid() {
		return orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	/**
	 */

	public void setRemark(String remark) {
		this.remark = remark;
	}

	/*
	 * To add non XDoclet-generated methods, create a file named
	 * xdoclet-TawSystemUserRefRoleForm.java containing the additional code and
	 * place it in your metadata/web directory.
	 */
	/**
	 * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
	 *      javax.servlet.http.HttpServletRequest)
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// reset any boolean data types to false

	}

}
