// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.boco.eoms.sheet.base.service.ejb;

import java.lang.Exception;
import java.lang.Object;
import java.lang.String;
import java.lang.Throwable;
import java.rmi.RemoteException;
import java.rmi.UnexpectedException;
import java.util.HashMap;
import javax.ejb.EJBHome;
import javax.ejb.EJBObject;
import javax.ejb.Handle;
import javax.ejb.RemoveException;
import javax.rmi.CORBA.Stub;
import javax.rmi.CORBA.Util;

import org.omg.CORBA.SystemException;
import org.omg.CORBA.portable.ApplicationException;
import org.omg.CORBA.portable.InputStream;
import org.omg.CORBA.portable.OutputStream;
import org.omg.CORBA.portable.RemarshalException;
import org.omg.CORBA.portable.ServantObject;

public class _SaveDataService_Stub extends Stub implements SaveDataService {

    private static final String[] _type_ids = {
            "RMI:com.boco.eoms.sheet.base.service.ejb.SaveDataService:0000000000000000",
            "RMI:javax.ejb.EJBObject:0000000000000000"
    };

    public String[] _ids() {
        return _type_ids;
    }

    public EJBHome getEJBHome() throws RemoteException {
        while (true) {
            if (!Util.isLocal(this)) {
                InputStream in = null;
                try {
                    try {
                        OutputStream out = _request("_get_EJBHome", true);
                        in = _invoke(out);
                        return (EJBHome) in.read_Object(EJBHome.class);
                    } catch (ApplicationException ex) {
                        in = ex.getInputStream();
                        String id = in.read_string();
                        throw new UnexpectedException(id);
                    } catch (RemarshalException ex) {
                        continue;
                    }
                } catch (SystemException ex) {
                    throw Util.mapSystemException(ex);
                } finally {
                    _releaseReply(in);
                }
            } else {
                ServantObject so = _servant_preinvoke("_get_EJBHome", javax.ejb.EJBObject.class);
                if (so == null) {
                    continue;
                }
                try {
                    EJBHome result = ((javax.ejb.EJBObject) so.servant).getEJBHome();
                    return (EJBHome) Util.copyObject(result, _orb());
                } catch (Throwable ex) {
                    Throwable exCopy = (Throwable) Util.copyObject(ex, _orb());
                    throw Util.wrapException(exCopy);
                } finally {
                    _servant_postinvoke(so);
                }
            }
        }
    }

    public Object getPrimaryKey() throws RemoteException {
        while (true) {
            if (!Util.isLocal(this)) {
                InputStream in = null;
                try {
                    try {
                        OutputStream out = _request("_get_primaryKey", true);
                        in = _invoke(out);
                        return Util.readAny(in);
                    } catch (ApplicationException ex) {
                        in = ex.getInputStream();
                        String id = in.read_string();
                        throw new UnexpectedException(id);
                    } catch (RemarshalException ex) {
                        continue;
                    }
                } catch (SystemException ex) {
                    throw Util.mapSystemException(ex);
                } finally {
                    _releaseReply(in);
                }
            } else {
                ServantObject so = _servant_preinvoke("_get_primaryKey", javax.ejb.EJBObject.class);
                if (so == null) {
                    continue;
                }
                try {
                    Object result = ((javax.ejb.EJBObject) so.servant).getPrimaryKey();
                    return (Object) Util.copyObject(result, _orb());
                } catch (Throwable ex) {
                    Throwable exCopy = (Throwable) Util.copyObject(ex, _orb());
                    throw Util.wrapException(exCopy);
                } finally {
                    _servant_postinvoke(so);
                }
            }
        }
    }

    public void remove() throws RemoteException, RemoveException {
        while (true) {
            if (!Util.isLocal(this)) {
                org.omg.CORBA_2_3.portable.InputStream in = null;
                try {
                    try {
                        OutputStream out = _request("remove", true);
                        _invoke(out);
                        return;
                    } catch (ApplicationException ex) {
                        in = (org.omg.CORBA_2_3.portable.InputStream) ex.getInputStream();
                        String id = in.read_string();
                        if (id.equals("IDL:javax/ejb/RemoveEx:1.0")) {
                            throw (RemoveException) in.read_value(RemoveException.class);
                        }
                        throw new UnexpectedException(id);
                    } catch (RemarshalException ex) {
                        continue;
                    }
                } catch (SystemException ex) {
                    throw Util.mapSystemException(ex);
                } finally {
                    _releaseReply(in);
                }
            } else {
                ServantObject so = _servant_preinvoke("remove", javax.ejb.EJBObject.class);
                if (so == null) {
                    continue;
                }
                try {
                    ((javax.ejb.EJBObject) so.servant).remove();
                    return;
                } catch (Throwable ex) {
                    Throwable exCopy = (Throwable) Util.copyObject(ex, _orb());
                    if (exCopy instanceof RemoveException) {
                        throw (RemoveException) exCopy;
                    }
                    throw Util.wrapException(exCopy);
                } finally {
                    _servant_postinvoke(so);
                }
            }
        }
    }

    public Handle getHandle() throws RemoteException {
        while (true) {
            if (!Util.isLocal(this)) {
                org.omg.CORBA_2_3.portable.InputStream in = null;
                try {
                    try {
                        OutputStream out = _request("_get_handle", true);
                        in = (org.omg.CORBA_2_3.portable.InputStream) _invoke(out);
                        return (Handle) in.read_abstract_interface(Handle.class);
                    } catch (ApplicationException ex) {
                        in = (org.omg.CORBA_2_3.portable.InputStream) ex.getInputStream();
                        String id = in.read_string();
                        throw new UnexpectedException(id);
                    } catch (RemarshalException ex) {
                        continue;
                    }
                } catch (SystemException ex) {
                    throw Util.mapSystemException(ex);
                } finally {
                    _releaseReply(in);
                }
            } else {
                ServantObject so = _servant_preinvoke("_get_handle", javax.ejb.EJBObject.class);
                if (so == null) {
                    continue;
                }
                try {
                    Handle result = ((javax.ejb.EJBObject) so.servant).getHandle();
                    return (Handle) Util.copyObject(result, _orb());
                } catch (Throwable ex) {
                    Throwable exCopy = (Throwable) Util.copyObject(ex, _orb());
                    throw Util.wrapException(exCopy);
                } finally {
                    _servant_postinvoke(so);
                }
            }
        }
    }

    public boolean isIdentical(EJBObject arg0) throws RemoteException {
        while (true) {
            if (!Util.isLocal(this)) {
                InputStream in = null;
                try {
                    try {
                        OutputStream out = _request("isIdentical", true);
                        Util.writeRemoteObject(out, arg0);
                        in = _invoke(out);
                        return in.read_boolean();
                    } catch (ApplicationException ex) {
                        in = ex.getInputStream();
                        String id = in.read_string();
                        throw new UnexpectedException(id);
                    } catch (RemarshalException ex) {
                        continue;
                    }
                } catch (SystemException ex) {
                    throw Util.mapSystemException(ex);
                } finally {
                    _releaseReply(in);
                }
            } else {
                ServantObject so = _servant_preinvoke("isIdentical", javax.ejb.EJBObject.class);
                if (so == null) {
                    continue;
                }
                try {
                    EJBObject arg0Copy = (EJBObject) Util.copyObject(arg0, _orb());
                    return ((javax.ejb.EJBObject) so.servant).isIdentical(arg0Copy);
                } catch (Throwable ex) {
                    Throwable exCopy = (Throwable) Util.copyObject(ex, _orb());
                    throw Util.wrapException(exCopy);
                } finally {
                    _servant_postinvoke(so);
                }
            }
        }
    }

    public void saveMain(Object arg0, String arg1) throws Exception {
        while (true) {
            if (!Util.isLocal(this)) {
                org.omg.CORBA_2_3.portable.InputStream in = null;
                try {
                    try {
                        org.omg.CORBA_2_3.portable.OutputStream out =
                                (org.omg.CORBA_2_3.portable.OutputStream)
                                        _request("saveMain", true);
                        Util.writeAny(out, arg0);
                        out.write_value(arg1, String.class);
                        _invoke(out);
                        return;
                    } catch (ApplicationException ex) {
                        in = (org.omg.CORBA_2_3.portable.InputStream) ex.getInputStream();
                        String id = in.read_string();
                        if (id.equals("IDL:java/lang/Ex:1.0")) {
                            throw (Exception) in.read_value(Exception.class);
                        }
                        throw new UnexpectedException(id);
                    } catch (RemarshalException ex) {
                        continue;
                    }
                } catch (SystemException ex) {
                    throw Util.mapSystemException(ex);
                } finally {
                    _releaseReply(in);
                }
            } else {
                ServantObject so = _servant_preinvoke("saveMain", com.boco.eoms.sheet.base.service.ejb.SaveDataService.class);
                if (so == null) {
                    continue;
                }
                try {
                    Object[] copies = Util.copyObjects(new Object[]{arg0, arg1}, _orb());
                    Object arg0Copy = (Object) copies[0];
                    String arg1Copy = (String) copies[1];
                    ((com.boco.eoms.sheet.base.service.ejb.SaveDataService) so.servant).saveMain(arg0Copy, arg1Copy);
                    return;
                } catch (Throwable ex) {
                    Throwable exCopy = (Throwable) Util.copyObject(ex, _orb());
                    if (exCopy instanceof Exception) {
                        throw (Exception) exCopy;
                    }
                    throw Util.wrapException(exCopy);
                } finally {
                    _servant_postinvoke(so);
                }
            }
        }
    }

    public String saveLink(Object arg0, String arg1) throws Exception {
        while (true) {
            if (!Util.isLocal(this)) {
                org.omg.CORBA_2_3.portable.InputStream in = null;
                try {
                    try {
                        org.omg.CORBA_2_3.portable.OutputStream out =
                                (org.omg.CORBA_2_3.portable.OutputStream)
                                        _request("saveLink", true);
                        Util.writeAny(out, arg0);
                        out.write_value(arg1, String.class);
                        in = (org.omg.CORBA_2_3.portable.InputStream) _invoke(out);
                        return (String) in.read_value(String.class);
                    } catch (ApplicationException ex) {
                        in = (org.omg.CORBA_2_3.portable.InputStream) ex.getInputStream();
                        String id = in.read_string();
                        if (id.equals("IDL:java/lang/Ex:1.0")) {
                            throw (Exception) in.read_value(Exception.class);
                        }
                        throw new UnexpectedException(id);
                    } catch (RemarshalException ex) {
                        continue;
                    }
                } catch (SystemException ex) {
                    throw Util.mapSystemException(ex);
                } finally {
                    _releaseReply(in);
                }
            } else {
                ServantObject so = _servant_preinvoke("saveLink", com.boco.eoms.sheet.base.service.ejb.SaveDataService.class);
                if (so == null) {
                    continue;
                }
                try {
                    Object[] copies = Util.copyObjects(new Object[]{arg0, arg1}, _orb());
                    Object arg0Copy = (Object) copies[0];
                    String arg1Copy = (String) copies[1];
                    return ((com.boco.eoms.sheet.base.service.ejb.SaveDataService) so.servant).saveLink(arg0Copy, arg1Copy);
                } catch (Throwable ex) {
                    Throwable exCopy = (Throwable) Util.copyObject(ex, _orb());
                    if (exCopy instanceof Exception) {
                        throw (Exception) exCopy;
                    }
                    throw Util.wrapException(exCopy);
                } finally {
                    _servant_postinvoke(so);
                }
            }
        }
    }

    public void saveTask(HashMap arg0, String arg1) throws Exception {
        while (true) {
            if (!Util.isLocal(this)) {
                org.omg.CORBA_2_3.portable.InputStream in = null;
                try {
                    try {
                        org.omg.CORBA_2_3.portable.OutputStream out =
                                (org.omg.CORBA_2_3.portable.OutputStream)
                                        _request("saveTask", true);
                        out.write_value(arg0, HashMap.class);
                        out.write_value(arg1, String.class);
                        _invoke(out);
                        return;
                    } catch (ApplicationException ex) {
                        in = (org.omg.CORBA_2_3.portable.InputStream) ex.getInputStream();
                        String id = in.read_string();
                        if (id.equals("IDL:java/lang/Ex:1.0")) {
                            throw (Exception) in.read_value(Exception.class);
                        }
                        throw new UnexpectedException(id);
                    } catch (RemarshalException ex) {
                        continue;
                    }
                } catch (SystemException ex) {
                    throw Util.mapSystemException(ex);
                } finally {
                    _releaseReply(in);
                }
            } else {
                ServantObject so = _servant_preinvoke("saveTask", com.boco.eoms.sheet.base.service.ejb.SaveDataService.class);
                if (so == null) {
                    continue;
                }
                try {
                    Object[] copies = Util.copyObjects(new Object[]{arg0, arg1}, _orb());
                    HashMap arg0Copy = (HashMap) copies[0];
                    String arg1Copy = (String) copies[1];
                    ((com.boco.eoms.sheet.base.service.ejb.SaveDataService) so.servant).saveTask(arg0Copy, arg1Copy);
                    return;
                } catch (Throwable ex) {
                    Throwable exCopy = (Throwable) Util.copyObject(ex, _orb());
                    if (exCopy instanceof Exception) {
                        throw (Exception) exCopy;
                    }
                    throw Util.wrapException(exCopy);
                } finally {
                    _servant_postinvoke(so);
                }
            }
        }
    }

    public void saveOrUpdateMain(Object arg0, String arg1) throws Exception {
        while (true) {
            if (!Util.isLocal(this)) {
                org.omg.CORBA_2_3.portable.InputStream in = null;
                try {
                    try {
                        org.omg.CORBA_2_3.portable.OutputStream out =
                                (org.omg.CORBA_2_3.portable.OutputStream)
                                        _request("saveOrUpdateMain", true);
                        Util.writeAny(out, arg0);
                        out.write_value(arg1, String.class);
                        _invoke(out);
                        return;
                    } catch (ApplicationException ex) {
                        in = (org.omg.CORBA_2_3.portable.InputStream) ex.getInputStream();
                        String id = in.read_string();
                        if (id.equals("IDL:java/lang/Ex:1.0")) {
                            throw (Exception) in.read_value(Exception.class);
                        }
                        throw new UnexpectedException(id);
                    } catch (RemarshalException ex) {
                        continue;
                    }
                } catch (SystemException ex) {
                    throw Util.mapSystemException(ex);
                } finally {
                    _releaseReply(in);
                }
            } else {
                ServantObject so = _servant_preinvoke("saveOrUpdateMain", com.boco.eoms.sheet.base.service.ejb.SaveDataService.class);
                if (so == null) {
                    continue;
                }
                try {
                    Object[] copies = Util.copyObjects(new Object[]{arg0, arg1}, _orb());
                    Object arg0Copy = (Object) copies[0];
                    String arg1Copy = (String) copies[1];
                    ((com.boco.eoms.sheet.base.service.ejb.SaveDataService) so.servant).saveOrUpdateMain(arg0Copy, arg1Copy);
                    return;
                } catch (Throwable ex) {
                    Throwable exCopy = (Throwable) Util.copyObject(ex, _orb());
                    if (exCopy instanceof Exception) {
                        throw (Exception) exCopy;
                    }
                    throw Util.wrapException(exCopy);
                } finally {
                    _servant_postinvoke(so);
                }
            }
        }
    }

    public String saveOrUpdateLink(Object arg0, String arg1) throws Exception {
        while (true) {
            if (!Util.isLocal(this)) {
                org.omg.CORBA_2_3.portable.InputStream in = null;
                try {
                    try {
                        org.omg.CORBA_2_3.portable.OutputStream out =
                                (org.omg.CORBA_2_3.portable.OutputStream)
                                        _request("saveOrUpdateLink", true);
                        Util.writeAny(out, arg0);
                        out.write_value(arg1, String.class);
                        in = (org.omg.CORBA_2_3.portable.InputStream) _invoke(out);
                        return (String) in.read_value(String.class);
                    } catch (ApplicationException ex) {
                        in = (org.omg.CORBA_2_3.portable.InputStream) ex.getInputStream();
                        String id = in.read_string();
                        if (id.equals("IDL:java/lang/Ex:1.0")) {
                            throw (Exception) in.read_value(Exception.class);
                        }
                        throw new UnexpectedException(id);
                    } catch (RemarshalException ex) {
                        continue;
                    }
                } catch (SystemException ex) {
                    throw Util.mapSystemException(ex);
                } finally {
                    _releaseReply(in);
                }
            } else {
                ServantObject so = _servant_preinvoke("saveOrUpdateLink", com.boco.eoms.sheet.base.service.ejb.SaveDataService.class);
                if (so == null) {
                    continue;
                }
                try {
                    Object[] copies = Util.copyObjects(new Object[]{arg0, arg1}, _orb());
                    Object arg0Copy = (Object) copies[0];
                    String arg1Copy = (String) copies[1];
                    return ((com.boco.eoms.sheet.base.service.ejb.SaveDataService) so.servant).saveOrUpdateLink(arg0Copy, arg1Copy);
                } catch (Throwable ex) {
                    Throwable exCopy = (Throwable) Util.copyObject(ex, _orb());
                    if (exCopy instanceof Exception) {
                        throw (Exception) exCopy;
                    }
                    throw Util.wrapException(exCopy);
                } finally {
                    _servant_postinvoke(so);
                }
            }
        }
    }

    public void saveOrUpdateTask(HashMap arg0, String arg1) throws Exception {
        while (true) {
            if (!Util.isLocal(this)) {
                org.omg.CORBA_2_3.portable.InputStream in = null;
                try {
                    try {
                        org.omg.CORBA_2_3.portable.OutputStream out =
                                (org.omg.CORBA_2_3.portable.OutputStream)
                                        _request("saveOrUpdateTask", true);
                        out.write_value(arg0, HashMap.class);
                        out.write_value(arg1, String.class);
                        _invoke(out);
                        return;
                    } catch (ApplicationException ex) {
                        in = (org.omg.CORBA_2_3.portable.InputStream) ex.getInputStream();
                        String id = in.read_string();
                        if (id.equals("IDL:java/lang/Ex:1.0")) {
                            throw (Exception) in.read_value(Exception.class);
                        }
                        throw new UnexpectedException(id);
                    } catch (RemarshalException ex) {
                        continue;
                    }
                } catch (SystemException ex) {
                    throw Util.mapSystemException(ex);
                } finally {
                    _releaseReply(in);
                }
            } else {
                ServantObject so = _servant_preinvoke("saveOrUpdateTask", com.boco.eoms.sheet.base.service.ejb.SaveDataService.class);
                if (so == null) {
                    continue;
                }
                try {
                    Object[] copies = Util.copyObjects(new Object[]{arg0, arg1}, _orb());
                    HashMap arg0Copy = (HashMap) copies[0];
                    String arg1Copy = (String) copies[1];
                    ((com.boco.eoms.sheet.base.service.ejb.SaveDataService) so.servant).saveOrUpdateTask(arg0Copy, arg1Copy);
                    return;
                } catch (Throwable ex) {
                    Throwable exCopy = (Throwable) Util.copyObject(ex, _orb());
                    if (exCopy instanceof Exception) {
                        throw (Exception) exCopy;
                    }
                    throw Util.wrapException(exCopy);
                } finally {
                    _servant_postinvoke(so);
                }
            }
        }
    }

    public void updateMain(HashMap arg0, String arg1) throws Exception {
        while (true) {
            if (!Util.isLocal(this)) {
                org.omg.CORBA_2_3.portable.InputStream in = null;
                try {
                    try {
                        org.omg.CORBA_2_3.portable.OutputStream out =
                                (org.omg.CORBA_2_3.portable.OutputStream)
                                        _request("updateMain", true);
                        out.write_value(arg0, HashMap.class);
                        out.write_value(arg1, String.class);
                        _invoke(out);
                        return;
                    } catch (ApplicationException ex) {
                        in = (org.omg.CORBA_2_3.portable.InputStream) ex.getInputStream();
                        String id = in.read_string();
                        if (id.equals("IDL:java/lang/Ex:1.0")) {
                            throw (Exception) in.read_value(Exception.class);
                        }
                        throw new UnexpectedException(id);
                    } catch (RemarshalException ex) {
                        continue;
                    }
                } catch (SystemException ex) {
                    throw Util.mapSystemException(ex);
                } finally {
                    _releaseReply(in);
                }
            } else {
                ServantObject so = _servant_preinvoke("updateMain", com.boco.eoms.sheet.base.service.ejb.SaveDataService.class);
                if (so == null) {
                    continue;
                }
                try {
                    Object[] copies = Util.copyObjects(new Object[]{arg0, arg1}, _orb());
                    HashMap arg0Copy = (HashMap) copies[0];
                    String arg1Copy = (String) copies[1];
                    ((com.boco.eoms.sheet.base.service.ejb.SaveDataService) so.servant).updateMain(arg0Copy, arg1Copy);
                    return;
                } catch (Throwable ex) {
                    Throwable exCopy = (Throwable) Util.copyObject(ex, _orb());
                    if (exCopy instanceof Exception) {
                        throw (Exception) exCopy;
                    }
                    throw Util.wrapException(exCopy);
                } finally {
                    _servant_postinvoke(so);
                }
            }
        }
    }

    public void updateLink(HashMap arg0, String arg1) throws Exception {
        while (true) {
            if (!Util.isLocal(this)) {
                org.omg.CORBA_2_3.portable.InputStream in = null;
                try {
                    try {
                        org.omg.CORBA_2_3.portable.OutputStream out =
                                (org.omg.CORBA_2_3.portable.OutputStream)
                                        _request("updateLink", true);
                        out.write_value(arg0, HashMap.class);
                        out.write_value(arg1, String.class);
                        _invoke(out);
                        return;
                    } catch (ApplicationException ex) {
                        in = (org.omg.CORBA_2_3.portable.InputStream) ex.getInputStream();
                        String id = in.read_string();
                        if (id.equals("IDL:java/lang/Ex:1.0")) {
                            throw (Exception) in.read_value(Exception.class);
                        }
                        throw new UnexpectedException(id);
                    } catch (RemarshalException ex) {
                        continue;
                    }
                } catch (SystemException ex) {
                    throw Util.mapSystemException(ex);
                } finally {
                    _releaseReply(in);
                }
            } else {
                ServantObject so = _servant_preinvoke("updateLink", com.boco.eoms.sheet.base.service.ejb.SaveDataService.class);
                if (so == null) {
                    continue;
                }
                try {
                    Object[] copies = Util.copyObjects(new Object[]{arg0, arg1}, _orb());
                    HashMap arg0Copy = (HashMap) copies[0];
                    String arg1Copy = (String) copies[1];
                    ((com.boco.eoms.sheet.base.service.ejb.SaveDataService) so.servant).updateLink(arg0Copy, arg1Copy);
                    return;
                } catch (Throwable ex) {
                    Throwable exCopy = (Throwable) Util.copyObject(ex, _orb());
                    if (exCopy instanceof Exception) {
                        throw (Exception) exCopy;
                    }
                    throw Util.wrapException(exCopy);
                } finally {
                    _servant_postinvoke(so);
                }
            }
        }
    }

    public void updateTask(HashMap arg0, String arg1) throws Exception {
        while (true) {
            if (!Util.isLocal(this)) {
                org.omg.CORBA_2_3.portable.InputStream in = null;
                try {
                    try {
                        org.omg.CORBA_2_3.portable.OutputStream out =
                                (org.omg.CORBA_2_3.portable.OutputStream)
                                        _request("updateTask", true);
                        out.write_value(arg0, HashMap.class);
                        out.write_value(arg1, String.class);
                        _invoke(out);
                        return;
                    } catch (ApplicationException ex) {
                        in = (org.omg.CORBA_2_3.portable.InputStream) ex.getInputStream();
                        String id = in.read_string();
                        if (id.equals("IDL:java/lang/Ex:1.0")) {
                            throw (Exception) in.read_value(Exception.class);
                        }
                        throw new UnexpectedException(id);
                    } catch (RemarshalException ex) {
                        continue;
                    }
                } catch (SystemException ex) {
                    throw Util.mapSystemException(ex);
                } finally {
                    _releaseReply(in);
                }
            } else {
                ServantObject so = _servant_preinvoke("updateTask", com.boco.eoms.sheet.base.service.ejb.SaveDataService.class);
                if (so == null) {
                    continue;
                }
                try {
                    Object[] copies = Util.copyObjects(new Object[]{arg0, arg1}, _orb());
                    HashMap arg0Copy = (HashMap) copies[0];
                    String arg1Copy = (String) copies[1];
                    ((com.boco.eoms.sheet.base.service.ejb.SaveDataService) so.servant).updateTask(arg0Copy, arg1Copy);
                    return;
                } catch (Throwable ex) {
                    Throwable exCopy = (Throwable) Util.copyObject(ex, _orb());
                    if (exCopy instanceof Exception) {
                        throw (Exception) exCopy;
                    }
                    throw Util.wrapException(exCopy);
                } finally {
                    _servant_postinvoke(so);
                }
            }
        }
    }

    public void updateTaskByStatus(String arg0, String arg1) throws Exception {
        while (true) {
            if (!Util.isLocal(this)) {
                org.omg.CORBA_2_3.portable.InputStream in = null;
                try {
                    try {
                        org.omg.CORBA_2_3.portable.OutputStream out =
                                (org.omg.CORBA_2_3.portable.OutputStream)
                                        _request("updateTaskByStatus", true);
                        out.write_value(arg0, String.class);
                        out.write_value(arg1, String.class);
                        _invoke(out);
                        return;
                    } catch (ApplicationException ex) {
                        in = (org.omg.CORBA_2_3.portable.InputStream) ex.getInputStream();
                        String id = in.read_string();
                        if (id.equals("IDL:java/lang/Ex:1.0")) {
                            throw (Exception) in.read_value(Exception.class);
                        }
                        throw new UnexpectedException(id);
                    } catch (RemarshalException ex) {
                        continue;
                    }
                } catch (SystemException ex) {
                    throw Util.mapSystemException(ex);
                } finally {
                    _releaseReply(in);
                }
            } else {
                ServantObject so = _servant_preinvoke("updateTaskByStatus", com.boco.eoms.sheet.base.service.ejb.SaveDataService.class);
                if (so == null) {
                    continue;
                }
                try {
                    ((com.boco.eoms.sheet.base.service.ejb.SaveDataService) so.servant).updateTaskByStatus(arg0, arg1);
                    return;
                } catch (Throwable ex) {
                    Throwable exCopy = (Throwable) Util.copyObject(ex, _orb());
                    if (exCopy instanceof Exception) {
                        throw (Exception) exCopy;
                    }
                    throw Util.wrapException(exCopy);
                } finally {
                    _servant_postinvoke(so);
                }
            }
        }
    }

    public void updateTaskBySubTaskFlag(String arg0, String arg1, String arg2) throws Exception {
        while (true) {
            if (!Util.isLocal(this)) {
                org.omg.CORBA_2_3.portable.InputStream in = null;
                try {
                    try {
                        org.omg.CORBA_2_3.portable.OutputStream out =
                                (org.omg.CORBA_2_3.portable.OutputStream)
                                        _request("updateTaskBySubTaskFlag", true);
                        out.write_value(arg0, String.class);
                        out.write_value(arg1, String.class);
                        out.write_value(arg2, String.class);
                        _invoke(out);
                        return;
                    } catch (ApplicationException ex) {
                        in = (org.omg.CORBA_2_3.portable.InputStream) ex.getInputStream();
                        String id = in.read_string();
                        if (id.equals("IDL:java/lang/Ex:1.0")) {
                            throw (Exception) in.read_value(Exception.class);
                        }
                        throw new UnexpectedException(id);
                    } catch (RemarshalException ex) {
                        continue;
                    }
                } catch (SystemException ex) {
                    throw Util.mapSystemException(ex);
                } finally {
                    _releaseReply(in);
                }
            } else {
                ServantObject so = _servant_preinvoke("updateTaskBySubTaskFlag", com.boco.eoms.sheet.base.service.ejb.SaveDataService.class);
                if (so == null) {
                    continue;
                }
                try {
                    ((com.boco.eoms.sheet.base.service.ejb.SaveDataService) so.servant).updateTaskBySubTaskFlag(arg0, arg1, arg2);
                    return;
                } catch (Throwable ex) {
                    Throwable exCopy = (Throwable) Util.copyObject(ex, _orb());
                    if (exCopy instanceof Exception) {
                        throw (Exception) exCopy;
                    }
                    throw Util.wrapException(exCopy);
                } finally {
                    _servant_postinvoke(so);
                }
            }
        }
    }

    public void updateSheetRelationState(String arg0) throws Exception {
        while (true) {
            if (!Util.isLocal(this)) {
                org.omg.CORBA_2_3.portable.InputStream in = null;
                try {
                    try {
                        org.omg.CORBA_2_3.portable.OutputStream out =
                                (org.omg.CORBA_2_3.portable.OutputStream)
                                        _request("updateSheetRelationState", true);
                        out.write_value(arg0, String.class);
                        _invoke(out);
                        return;
                    } catch (ApplicationException ex) {
                        in = (org.omg.CORBA_2_3.portable.InputStream) ex.getInputStream();
                        String id = in.read_string();
                        if (id.equals("IDL:java/lang/Ex:1.0")) {
                            throw (Exception) in.read_value(Exception.class);
                        }
                        throw new UnexpectedException(id);
                    } catch (RemarshalException ex) {
                        continue;
                    }
                } catch (SystemException ex) {
                    throw Util.mapSystemException(ex);
                } finally {
                    _releaseReply(in);
                }
            } else {
                ServantObject so = _servant_preinvoke("updateSheetRelationState", com.boco.eoms.sheet.base.service.ejb.SaveDataService.class);
                if (so == null) {
                    continue;
                }
                try {
                    ((com.boco.eoms.sheet.base.service.ejb.SaveDataService) so.servant).updateSheetRelationState(arg0);
                    return;
                } catch (Throwable ex) {
                    Throwable exCopy = (Throwable) Util.copyObject(ex, _orb());
                    if (exCopy instanceof Exception) {
                        throw (Exception) exCopy;
                    }
                    throw Util.wrapException(exCopy);
                } finally {
                    _servant_postinvoke(so);
                }
            }
        }
    }

    public void updateTaskState(String arg0, String arg1, String arg2) throws Exception {
        while (true) {
            if (!Util.isLocal(this)) {
                org.omg.CORBA_2_3.portable.InputStream in = null;
                try {
                    try {
                        org.omg.CORBA_2_3.portable.OutputStream out =
                                (org.omg.CORBA_2_3.portable.OutputStream)
                                        _request("updateTaskState", true);
                        out.write_value(arg0, String.class);
                        out.write_value(arg1, String.class);
                        out.write_value(arg2, String.class);
                        _invoke(out);
                        return;
                    } catch (ApplicationException ex) {
                        in = (org.omg.CORBA_2_3.portable.InputStream) ex.getInputStream();
                        String id = in.read_string();
                        if (id.equals("IDL:java/lang/Ex:1.0")) {
                            throw (Exception) in.read_value(Exception.class);
                        }
                        throw new UnexpectedException(id);
                    } catch (RemarshalException ex) {
                        continue;
                    }
                } catch (SystemException ex) {
                    throw Util.mapSystemException(ex);
                } finally {
                    _releaseReply(in);
                }
            } else {
                ServantObject so = _servant_preinvoke("updateTaskState", com.boco.eoms.sheet.base.service.ejb.SaveDataService.class);
                if (so == null) {
                    continue;
                }
                try {
                    ((com.boco.eoms.sheet.base.service.ejb.SaveDataService) so.servant).updateTaskState(arg0, arg1, arg2);
                    return;
                } catch (Throwable ex) {
                    Throwable exCopy = (Throwable) Util.copyObject(ex, _orb());
                    if (exCopy instanceof Exception) {
                        throw (Exception) exCopy;
                    }
                    throw Util.wrapException(exCopy);
                } finally {
                    _servant_postinvoke(so);
                }
            }
        }
    }

    public String getUUID() throws Exception {
        while (true) {
            if (!Util.isLocal(this)) {
                org.omg.CORBA_2_3.portable.InputStream in = null;
                try {
                    try {
                        OutputStream out = _request("getUUID", true);
                        in = (org.omg.CORBA_2_3.portable.InputStream) _invoke(out);
                        return (String) in.read_value(String.class);
                    } catch (ApplicationException ex) {
                        in = (org.omg.CORBA_2_3.portable.InputStream) ex.getInputStream();
                        String id = in.read_string();
                        if (id.equals("IDL:java/lang/Ex:1.0")) {
                            throw (Exception) in.read_value(Exception.class);
                        }
                        throw new UnexpectedException(id);
                    } catch (RemarshalException ex) {
                        continue;
                    }
                } catch (SystemException ex) {
                    throw Util.mapSystemException(ex);
                } finally {
                    _releaseReply(in);
                }
            } else {
                ServantObject so = _servant_preinvoke("getUUID", com.boco.eoms.sheet.base.service.ejb.SaveDataService.class);
                if (so == null) {
                    continue;
                }
                try {
                    return ((com.boco.eoms.sheet.base.service.ejb.SaveDataService) so.servant).getUUID();
                } catch (Throwable ex) {
                    Throwable exCopy = (Throwable) Util.copyObject(ex, _orb());
                    if (exCopy instanceof Exception) {
                        throw (Exception) exCopy;
                    }
                    throw Util.wrapException(exCopy);
                } finally {
                    _servant_postinvoke(so);
                }
            }
        }
    }

    public void invokeWfInterface(String arg0, String arg1, String arg2, String arg3, String arg4, String arg5, String arg6) throws Exception {
        while (true) {
            if (!Util.isLocal(this)) {
                org.omg.CORBA_2_3.portable.InputStream in = null;
                try {
                    try {
                        org.omg.CORBA_2_3.portable.OutputStream out =
                                (org.omg.CORBA_2_3.portable.OutputStream)
                                        _request("invokeWfInterface", true);
                        out.write_value(arg0, String.class);
                        out.write_value(arg1, String.class);
                        out.write_value(arg2, String.class);
                        out.write_value(arg3, String.class);
                        out.write_value(arg4, String.class);
                        out.write_value(arg5, String.class);
                        out.write_value(arg6, String.class);
                        _invoke(out);
                        return;
                    } catch (ApplicationException ex) {
                        in = (org.omg.CORBA_2_3.portable.InputStream) ex.getInputStream();
                        String id = in.read_string();
                        if (id.equals("IDL:java/lang/Ex:1.0")) {
                            throw (Exception) in.read_value(Exception.class);
                        }
                        throw new UnexpectedException(id);
                    } catch (RemarshalException ex) {
                        continue;
                    }
                } catch (SystemException ex) {
                    throw Util.mapSystemException(ex);
                } finally {
                    _releaseReply(in);
                }
            } else {
                ServantObject so = _servant_preinvoke("invokeWfInterface", com.boco.eoms.sheet.base.service.ejb.SaveDataService.class);
                if (so == null) {
                    continue;
                }
                try {
                    ((com.boco.eoms.sheet.base.service.ejb.SaveDataService) so.servant).invokeWfInterface(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                    return;
                } catch (Throwable ex) {
                    Throwable exCopy = (Throwable) Util.copyObject(ex, _orb());
                    if (exCopy instanceof Exception) {
                        throw (Exception) exCopy;
                    }
                    throw Util.wrapException(exCopy);
                } finally {
                    _servant_postinvoke(so);
                }
            }
        }
    }
}
