package com.boco.eoms.message.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with
 * XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 * 
 * @struts.form name="SmsContentTemplateForm"
 */
public class MmsSendForm extends BaseForm implements java.io.Serializable {
	
	protected String mobiles;
	
	protected String subject;
	
	protected String txtContent;
	
	protected String accessories;
	
	protected String contentType;
	
	protected String remark;
	
	



	public String getAccessories() {
		return accessories;
	}




	public void setAccessories(String accessories) {
		this.accessories = accessories;
	}




	public String getMobiles() {
		return mobiles;
	}




	public void setMobiles(String mobiles) {
		this.mobiles = mobiles;
	}




	public String getRemark() {
		return remark;
	}




	public void setRemark(String remark) {
		this.remark = remark;
	}

	

	public String getContentType() {
		return contentType;
	}




	public void setContentType(String contentType) {
		this.contentType = contentType;
	}




	public String getSubject() {
		return subject;
	}




	public void setSubject(String subject) {
		this.subject = subject;
	}

	


	public String getTxtContent() {
		return txtContent;
	}




	public void setTxtContent(String txtContent) {
		this.txtContent = txtContent;
	}




	/*
	 * To add non XDoclet-generated methods, create a file named
	 * xdoclet-SmsLogForm.java containing the additional code and place it in
	 * your metadata/web directory.
	 */
	/**
	 * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
	 *      javax.servlet.http.HttpServletRequest)
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// reset any boolean data types to false

	}

}
