package com.boco.eoms.message.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;

import com.boco.eoms.base.webapp.form.BaseForm;
/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="smsModuleForm" 
 */
public class SmsModuleForm extends BaseForm 
  implements java.io.Serializable {
	protected String id;

    protected String name;

    protected String parentId;

    protected String userId;

    protected String leaf;
    
    protected String deleted;

    protected String remark;
    
    /** Default empty constructor. */
    public SmsModuleForm() {}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getLeaf() {
		return leaf;
	}
	/**
	  * @struts.validator type="required"
	  */
	public void setLeaf(String leaf) {
		this.leaf = leaf;
	}

	public String getName() {
		return name;
	}
	/**
	  * @struts.validator type="required"
	  */
	public void setName(String name) {
		this.name = name;
	}

	public String getParentId() {
		return parentId;
	}
	/**
	  * @struts.validator type="required"
	  */
	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	public String getRemark() {
		return remark;
	}
	/**
	  * @struts.validator type="required"
	  */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getUserId() {
		return userId;
	}
	/**
	  * @struts.validator type="required"
	  */
	public void setUserId(String userId) {
		this.userId = userId;
	}
	/**
	  * @struts.validator type="required"
	  */
	public String getDeleted() {
		return deleted;
	}

	public void setDeleted(String deleted) {
		this.deleted = deleted;
	}

	/* To add non XDoclet-generated methods, create a file named
    xdoclet-SmsApplyForm.java 
    containing the additional code and place it in your metadata/web directory.
	 */
	/**
	* @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
	*                                                javax.servlet.http.HttpServletRequest)
	*/
	public void reset(ActionMapping mapping, HttpServletRequest request) {
	 // reset any boolean data types to false
	
	}
    
    

}
