package com.boco.eoms.message.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with
 * XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 * 
 * @struts.form name="smsMonitorForm"
 */
public class SmsMonitorForm extends BaseForm implements java.io.Serializable {

	protected String applyId;

	protected String content;

	protected String buizid;

	protected String dispatchTime;

	protected String id;

	protected String mobile;
	
	protected String isSendNight;

	protected String receiverId;
	
	protected String deleted;
	

	/** Default empty constructor. */
	public SmsMonitorForm() {
	}

	public String getApplyId() {
		return this.applyId;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setApplyId(String applyId) {
		this.applyId = applyId;
	}

	public String getContent() {
		return this.content;
	}

	public String getIsSendNight() {
		return isSendNight;
	}
	/**
	 * @struts.validator type="required"
	 */
	public void setIsSendNight(String isSendNight) {
		this.isSendNight = isSendNight;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setContent(String content) {
		this.content = content;
	}

	public String getDispatchTime() {
		return this.dispatchTime;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setDispatchTime(String dispatchTime) {
		this.dispatchTime = dispatchTime;
	}

	public String getId() {
		return this.id;
	}

	/**
	 */

	public void setId(String id) {
		this.id = id;
	}

	public String getMobile() {
		return this.mobile;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getReceiverId() {
		return this.receiverId;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setReceiverId(String receiverId) {
		this.receiverId = receiverId;
	}

	public String getBuizid() {
		return buizid;
	}
	/**
	 * @struts.validator type="required"
	 */
	public void setBuizid(String buizid) {
		this.buizid = buizid;
	}
	
	public String getDeleted() {
		return deleted;
	}
	/**
	 * @struts.validator type="required"
	 */
	public void setDeleted(String deleted) {
		this.deleted = deleted;
	}

	/*
	 * To add non XDoclet-generated methods, create a file named
	 * xdoclet-SmsMonitorForm.java containing the additional code and place it
	 * in your metadata/web directory.
	 */
	/**
	 * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
	 *      javax.servlet.http.HttpServletRequest)
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// reset any boolean data types to false

	}

}
