package com.boco.eoms.message.test.dao;

import java.util.List;

import com.boco.eoms.base.test.dao.BaseDaoTestCase;
import com.boco.eoms.message.model.SmsContentTemplate;
import com.boco.eoms.message.dao.ISmsContentTemplateDao;

import org.springframework.orm.ObjectRetrievalFailureException;

public class SmsContentTemplateDaoTest extends BaseDaoTestCase {
    private String smsContentTemplateId = new String("1");
    private ISmsContentTemplateDao dao = null;

    public void setSmsContentTemplateDao(ISmsContentTemplateDao dao) {
        this.dao = dao;
    }

    public void testAddSmsContentTemplate() throws Exception {
        SmsContentTemplate smsContentTemplate = new SmsContentTemplate();

        // set required fields

        java.lang.String content = "KcNoDkVtGdNgOdZgLtNoObKoNqSoOhDlKzIfJbPwGvGxOiAuWzGzJpYtReBvLnAaEhNsBrLbZqZlDgZiEfEhMxYtZaGeIePfYaFxLjJfYyPsVpKhWcSwYoCvAiSfPbLpTtSjTtQzAnIqWzNvDxSaOcVyUzMvLtCiUpTsBtEqNmPnUrLsHjSlVwSqZwSlLnBhVgPeTuCcYmOqFvYjGzHnNmChYbQwPvAbBkNgVbLcOgIcBbYfRmUqEaZhCmWfNuIoYhUtWkGxTyJuTzCiToZuFcHwVmUaXaTtQmLzCxYaZlXsXgUeWtOmWrHxGaHqFuJkKdQhKfTaWeYpErYvDxDxRjEfLzPbTdZoIgHvFwPeJvEqGuUcFiEbHcBtXrTuUqMvMhRkAyBpKsJpImBiMvVtCoCkFoTxBfNfXaNzMxUjSyAcQwCdJmZcQmAuZjMqNbRzJrExUtXhVnCeHpAmDxSyWuQmDiMbFdOxZfJvDmZhOpDzKfUbMwXxUcXlCwJuPnHsFzSoKoWyJjPcKaExZuElPoBoVcCnAoJwEoVmJyGfFvKqQtIbEwZcLtYpKfUfHqLlCxPwXfXmRbUsGzAxKjCjFzWkMnPtWoUiBoTtMvUwJnLpEoBiOwCiZvJeQbZbWhPvClOwZyWqFuRjReUkGgJyYyLgAkCcSpUfIoUxTbNcOlEmTkYcGmFfQwYyIsOmReAuMdCzXlBqAgShZxXnZxIaImIrYzJxByXzQcNjRgMvYqJsUwWeNvFxPmNlOqDiEtLzKlFpMiQdXdPmRpPoPaIcHbBiOfMaAzWiVhJoTaLqLrCgUrFzDxCaTaOoGoUbYvNwGxTcHiKyHiNjUyKqTrJxDxLoVaEwMlDaTaWrSgMrPzLmZbPaPuWmCpSlAzRjTrIgMnAlKnCtMaWsReTmRsKiQcGnOrPyWsIsOfGlKjLkXbSwRwCaZyTbKlFiHgKbOhYgUzLcTtBzPhSeFiIjIbEcZbRqIyOtJaVpKdByZqNkOtIvByYkCmZlOeOcJwTuOuZyAzUrYuQoMdIiTsWrKwLsWsVoOlIqXwJkVrPjTlQdQqDnIlDgMlBsIdYhHwBzFqBfFlZwHrVqXzTjDwJuHyTyNwLxOyZjHgKwNrMtKoHrCdXoVbUyLePlQqXwCbUhFwLoVvNcZyXlOsHuUeZxEwTzRjDbMpBeYwUwLcGwVjSoVaCvUjTdZmPgKdRuRgEuSmMuKnZiAbPaYdAgTyFsAmZvTmGwNeAfHmHxZkSwJiToPlEgTyEkBxCrQtXzXpNlBpDwZwRyHkAbRdLmOsQiPzDlScBnRoUtNgZcTuQgRbBlEjDpDwXyIdRxOhAdOxZzBvQsVtYkLwYpFeVtNoLyQhUhDdOhDsHmVwAvSnGlVrYtJyGhTvHpNeZoMtXjMtYuApUyTqZbGaMxDfWzNkUoRhWfKqWjXhYuGxXpJeTrIeQqXmJdMnJlBsIqXkIaPaOlNgToUzEzGgNdZkHhFgPaGhBbMgWoEpJdWdGtOxVtDnBmTcNaKwQoMgCbRgPnWyJtTnKxPlRsBfFfKaExAoVmTxQvDjNbGePzQuBhOrFxUeCzUrNxYiMzFoJnSfVdHnSlKsXlFfWbHeRqGxPxZhEkRuRzWlQjLuYsQvPrGsGlFdJoDiLlTcViSxKkJiVrBtJxRzIjGhDvQzJcJwGyDnOiMrTpBhHwGaIdAfPpZpIqBjRlBtCvVnKqLgGiGfJlPyBwHrBlVtBpUtTmWrUeFkPlRpKzWkKvLfUoZeXtPsLkKzKgZfSnMhRcZqEgIiUuJzWnSnHxPaGrQuRkAnMxWsHsWjVmIeDaWbEiVoCnRkWgDsGyOeGcKtYzZlGwZaPbFpYyYbVeYdQpDeZhKjSjPzHiTsDfIcQnTrPsBdXyIgKuQxQmSiDaSdGeGnWsYdXjEqZbRsGoTdEeMsCuUaPpXtTqGpCaUhLqLzWtIqVjIlGwBbJoQzShZzPgSvGsMaZhNkPjHhUdSeIbZnLzGoIfEyOaIpQzNnXlSzExMjPhCaGzGzXpUhSlGeTyMhDfFzWrZwEuWbOmCyNsHfBtFqWaVeDmHyFkJqBuQyNxSgQcWcOkVaEiBrYfAnOhZjAlLnSoMzAiJfHlYwTzGcBvNpJbGxSmPcQpCwSzRvIoIgVwOhDsDnYqSwQgJtPzUfYpUoOrMzFyKaVbCmDeZmInHaVdYuBwAuIoQyKmRmXmDoWcXuKqJyLkHlCbXbSnWaXlQuRmSrYjNfOcDpIlAbUkDrNvKaYmQlYsZoQyWxZvCyTpIvMwPfVcYvErXdLvJhLdWxFxNqDuAcAzNpGzFbDeDdNcKlQyUkAxFnLrApHgQyLeHwAxRaQwExXkFpRbWaCaAyQxNnYrEaNqNuJlTrHlUuJcRaLoHfGyPcDqItBnQgKmZxPsNaPbBaWsIhBhKdZlInHqBmHmDqMdJtMbIdZnFgKaEzIbHxJpNhOdPsMjHyYtOtHnUeVaEjVaLmSnGpKkQbZvWgJrAzBmCjAcAgEdYsMwEfIhJiHeQdVsCzLfItZoAiCrFbObQiIjOeMfHxEnPfMvHmGeWbSpUiUxLkUgFzIeBmDbNjZlUySrTtVbZjLqMvPlOcQcFrAeHkVgTdLrPbZhHeJjVvTuMhImScAxVaGwNqRyJeSiEoGgCaEdZrUrZhNoOxBjGtKgDnYoLlWuViTbLtZxZsSuEhMlLcZwFeOxPaMbXqWuFtHzGzFvPePdNnBkBjLjTcFiJlRbSfNuGuPtAlVgPtCjAxBsXqEmLgBhOsLuSmEoSiZuChHgTbBwGpRjXgQpMiByDyUjKhDcSnJqZpQsZyTgEnFfYxEnKbTqDvFoBoOuUqIqEfBiYqQbKeIyDgFfVrWhLyQnBkSqYcOpZvOdPmKuWtAwAeYwPnDaLrRuRhIbBqQgVdWfHoHzIoHjZgZaAeLwFvQvUlFpPyUoMmTpAbIvNoZeHdMiJdZvXfPlBtBbLgFdBqIlSeIsLfPkUtNbYxBhHqVrJoUaFpJn";
        smsContentTemplate.setContent(content);        

        dao.saveSmsContentTemplate(smsContentTemplate);

        // verify a primary key was assigned
        assertNotNull(smsContentTemplate.getId());

        // verify set fields are same after save
        assertEquals(content, smsContentTemplate.getContent());
    }

    public void testGetSmsContentTemplate() throws Exception {
        SmsContentTemplate smsContentTemplate = dao.getSmsContentTemplate("8a1584491b72fc67011b72febf340004");
        assertNotNull(smsContentTemplate);
    }

    public void testGetSmsContentTemplates() throws Exception {
        SmsContentTemplate smsContentTemplate = new SmsContentTemplate();

        List results = dao.getSmsContentTemplates(smsContentTemplate);
        assertTrue(results.size() > 0);
    }

    public void testSaveSmsContentTemplate() throws Exception {
        SmsContentTemplate smsContentTemplate = dao.getSmsContentTemplate(smsContentTemplateId);

        // update required fields
        java.lang.String content = "StZjCeTkTqRcPfLkWzRlPeEyIbUiKtTbVvZjSrWzNwKcEdUmLkWeOmIgGrQwJaUjRcBnXiJpIqEwOqKcYgVcXnLyHsWaXwYaWvOgPmDxKzTtZvPiDvPuUqZiRoGpQxGkIkKuSkBgFoNpMdSrNlUoUpWaOrDuJeYySqVuLnJtFwZkHqBhNgVyXaUbPhDyQtIkLiQjEyCvTxMhPtUmFpEaWiXpLxWpVjApWwUcDlZvKzGwPbHnZbWqUjOtTkHwBmHgTpZqDiBdLxUmUlTrSqMwDuNqCjYfVmWeTsOhLyJeRhEiPoVjXbZzOlGrShSePkSrVfWzZdBcGbZbZiWyOpKkKeRjOoPkRiJeUiPlXdIhDnEhOwDfPwByHnTxWiXiGsEeJvNpHmJoKfPzWsHnIzQpZgWhPrUkDnBhJdLgBpPcFkFgYdGeJdCbJnCvMgOhBsMtAzKeFdBdOtBfBuHsPaFzYsUqAwWuUaOaVcDzIwInTaElUlFzPyWgHhJiVnUgGzLqKjTuGxJvTfYhFmBvZwDkAeQjLpChXfElQzTyCsTkAaMtOwRrQxFqUyXfAkBmJvJbHcErLzIyMgOiWbAvGzVsRtVyOwDoLhNfKpApUgQfUxNkFvIlBqTiVcAfFlIyElLcOcCxIdGxTbPqRhPiEjSqFeKcYmMzFpWcTfUeUkSxHkJtGkOkNwJcTfLqLpXgQgLmEfKgXxHvDqOnGqNdSwUnQeSlGlFjTtVwNqNmPaLpHoCbSsWiTvUiBtXhZqRlFfEhHpVzXcAnOaHfItLdBkBdWpVnDbJtMzUdStYpUjJlEhLjHwMlUoZqTqRcYhYpNzAtHbQoNxWeUrOlToNfMjClQxZkLjMiQoMzMmJwAeQiVkIcFrViUaTsEkAzTsSvSjLcSeZnQgPeYqNiMoWsPtSkPhIpZkFzLuNwIlNlDcQuUzJaLnDmHoKfZlVqWpHvGjPeKrQfVbCtYyJeRhEnHoGqIbKrWiTiZoZlZwVhExNqHuIxOaXhYdChJnZhVnZyCuVnMtJnJoQaItRfQkEsQzFlHtMeHzLfHoUcMcBtJtPuFhWkYaLrWpJrYrElNfIqTeCvLgNtElNnJtEjAzCiDuZhBsJiQwIuKjKbFwTmFpBdDeUsRyKaLvWfYyDuZxWpAiQwBaQjBjPbAkZePyJePmZwEcRwQrNcMaGyWlYeLhIfLmUlQeJtLiQtYfJvLnOeMnMhMdStNzWpZeMgPfDqHrPrEfPvDkYwPbHqPcNjEyUzHyYkLgGjAfVxGvNsOzJmDtYlKhEzXnVxVxOmKzOjWkJxTyGfLsTlYaPaAeTdThBuOiDjRdZaWqExRtCcFmUyQbEaUyXrLsGlXaGmYcQfKfSeRvIzCfWiWoSwCoAbZuUvBnRuRqZiAaLfRuWwQvIeHtQwFrEsFjMaKvImIgOxMtNhVoOpBrOeXrLjLwAuAdZhLbXrVlQgCiClLxKwLsAvYsTzSkZzHmDrMwSgHiHuFrMeJaGzPkWnQhFhCtRxNgSuGhNhHpVvFmTdSpPsRvEeIvGxVuQiPrNnDaBoXpDrHiRlOvVgOnHmZdOkPdIwOwLlAoIbIsQwBjSnCbIrWkOcTyAxTlHbBhFgIzKgScFrYrHhYiKlBdDoAlWmFnNlRpUlFrOfCiQxYkNgWmVhXiEtJmFkFdJaRtRgAlLzVvZwYvXgJeGiXrGnEuQaSjIxAhWzFaPpXaOuUsMeBmIhIlUlBmDdQfIgLxPfFlHuXdVeWdDaXkKfGfIcCuGxPfClEiWxPbKnZwVqCgFgRbKgBwIgPbPnAtYpLhPxWnXeEvPaVqFfZsAsXuSsUcJlAcSdMxRpWhDmUqBmFkBeJgWmShMyMoLtDzYvVhQzCcRpKrAgSfIdLxFoFnQkSvMxVqKuSgHsRwLaUbNdBzVgTeWvLeHtFxGmMmRdXnRuCtWmDnJvDaLmMbFhFaZoQuMlPpDmMzLzUqJjRdXzKpEeLkShBcNcFvQmGiIbEeCdFnFxLpZsLnOhRsHdLqSnTrDuTyDrXhAyCnNiIlMpSbEsVdIyZaLiSeWsNsSgIcFzXaMiFwRmUbLrDkXtGvIsSpScLgKpYjSvSvXzUiAvKlVqLqUsKoCrBgNsCxUeHjYlYzYnAeJfFwAkMsNyQePbTdJtRvJkHqNeYlErKjBgOpQjQlVcFhZwOzVuTsBaEfGiFiWeEtPiNqYaSqApIbYaOpUaKgHtIvGuJeKmUlMdGfCwYqHyZaOzOhHnZqDiNpPbYoDtVhDdNlGjNxGiXoZfIpSzKjVpIrZjVaLfWbFhMgHiYcWjEaTfLiGoIgKyBkQkQaVjYhHaVlQlCfOhQzCjXxLeJuQaKsTmMlQdXuNpCeIaFxMgZmNrSuIpHnIqYqRgBcPlJiSsDsGeHkGzSaXxUeJmZbTzMaYcVrCtOkQbAfXaOkUkOmJbBdByFxGaTuDlLrFlUlRoAzBgObJbDeXwAvMxXzHdLdApSyLpVdKkBsXaYsXbUoVsHyIkOwReKdFnIeHwVfVxCmKwBkUzVuXrLpZhXwXoBoTjKvJyGdPyDiWdLyQqQwDaIfYcWyYqGyGnScPvDhPfCoRmRwGaPqOuMtQdSxFoCyZsQlXsTmQiGhMrLhHuWmOoNmEaPdTzGuMrBcSyFlRoTvOqZfNuIxZrJiQiEgOlIiDpOwFeTsZjLvGvOrAxGqDpGhIgMfPrTwJjFjMaSySpXjWsJwBeTsFmDjSaFnJjNpQlWgArGaUrWjVpQqNcQcZaJjCfFyKzRfEsQyPzFyTgPfXsYfOeShStPkZjAzQbNpNvTgDpVmIsXsUmWyKuWjCdXzJxViAnNbPmIvDnLnSoBiZbTvMkAeZkIlLhVvRmGlYjYeAxPjOiCnXgWqUsUyQiJdNjLcVeLaFwUmBxFgZjPhCkQvMgSsAiYnGfEkLySxUmVkGcIlUoEkWvMkVlMrPyOxBsLqAwDlZdGaTvNfAgWfGhJdDkUdYhTwQzVqFlFmBcJmEaKhXpEjUxDyIl";
        smsContentTemplate.setContent(content);        

        dao.saveSmsContentTemplate(smsContentTemplate);

        assertEquals(content, smsContentTemplate.getContent());
    }

    public void testRemoveSmsContentTemplate() throws Exception {
        String removeId = new String("3");
        dao.removeSmsContentTemplate(removeId);
        try {
            dao.getSmsContentTemplate(removeId);
            fail("smsContentTemplate found in database");
        } catch (ObjectRetrievalFailureException e) {
            assertNotNull(e.getMessage());
        }
    }
}
