package com.boco.eoms.commons.log.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with
 * XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="tawCommonLogDeployForm"
 */
public class TawCommonLogDeployForm extends BaseForm implements
        java.io.Serializable {

    private static final long serialVersionUID = 1L;

    protected String beginnotetime;

    protected String filesavepath;

    protected String id;

    protected String isdebug;

    protected String loglevel;

    protected String modelid;

    protected String modelname;

    protected String noteremark;

    protected String operdesc;

    protected String operid;

    protected String opername;

    protected String userid;

    protected String savetype;

    protected String filecutsize;

    /**
     * Default empty constructor.
     */
    public TawCommonLogDeployForm() {
    }

    public String getBeginnotetime() {
        return this.beginnotetime;
    }

    /**
     *
     */

    public void setBeginnotetime(String beginnotetime) {
        this.beginnotetime = beginnotetime;
    }

    public String getFilesavepath() {
        return this.filesavepath;
    }

    /**
     *
     */

    public void setFilesavepath(String filesavepath) {
        this.filesavepath = filesavepath;
    }

    public String getId() {
        return this.id;
    }

    /**
     *
     */

    public void setId(String id) {
        this.id = id;
    }

    public String getIsdebug() {
        return this.isdebug;
    }

    /**
     *
     */

    public void setIsdebug(String isdebug) {
        this.isdebug = isdebug;
    }

    public String getLoglevel() {
        return this.loglevel;
    }

    /**
     *
     */

    public void setLoglevel(String loglevel) {
        this.loglevel = loglevel;
    }

    public String getModelid() {
        return this.modelid;
    }

    /**
     *
     */

    public void setModelid(String modelid) {
        this.modelid = modelid;
    }

    public String getModelname() {
        return this.modelname;
    }

    /**
     *
     */

    public void setModelname(String modelname) {
        this.modelname = modelname;
    }

    public String getNoteremark() {
        return this.noteremark;
    }

    /**
     *
     */

    public void setNoteremark(String noteremark) {
        this.noteremark = noteremark;
    }

    public String getOperdesc() {
        return this.operdesc;
    }

    /**
     *
     */

    public void setOperdesc(String operdesc) {
        this.operdesc = operdesc;
    }

    public String getOperid() {
        return this.operid;
    }

    /**
     *
     */

    public void setOperid(String operid) {
        this.operid = operid;
    }

    public String getOpername() {
        return this.opername;
    }

    /**
     *
     */

    public void setOpername(String opername) {
        this.opername = opername;
    }

    public String getUserid() {
        return this.userid;
    }

    /**
     *
     */

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getSavetype() {
        return this.savetype;
    }

    /**
     *
     */

    public void setSavetype(String savetype) {
        this.savetype = savetype;
    }

    public String getFilecutsize() {
        return this.filecutsize;
    }

    /**
     *
     */

    public void setFilecutsize(String filecutsize) {
        this.filecutsize = filecutsize;
    }

    /*
     * To add non XDoclet-generated methods, create a file named
     * xdoclet-TawCommonLogDeployForm.java containing the additional code and
     * place it in your metadata/web directory.
     */

    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     * javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

}
