package com.boco.eoms.commons.log.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with
 * XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 * 
 * @struts.form name="tawCommonLogOperatorForm"
 */
public class TawCommonLogOperatorForm extends BaseForm implements
		java.io.Serializable {

	private static final long serialVersionUID = 1L;

	protected String beginnotetime;

	protected String bzremark;

	protected String currentday;

	protected String currentmonth;

	protected String id;

	protected String issucess;

	protected String modelid;

	protected String modelname;

	protected String notemessage;

	protected String operatetime;

	protected String operid;

	protected String opername;

	protected String operremark;

	protected String remoteip;

	protected String url;

	protected String userid;

	/** Default empty constructor. */
	public TawCommonLogOperatorForm() {
	}

	public String getBeginnotetime() {
		return this.beginnotetime;
	}

	/**
	 */

	public void setBeginnotetime(String beginnotetime) {
		this.beginnotetime = beginnotetime;
	}

	public String getBzremark() {
		return this.bzremark;
	}

	/**
	 */

	public void setBzremark(String bzremark) {
		this.bzremark = bzremark;
	}

	public String getCurrentday() {
		return this.currentday;
	}

	/**
	 */

	public void setCurrentday(String currentday) {
		this.currentday = currentday;
	}

	public String getCurrentmonth() {
		return this.currentmonth;
	}

	/**
	 */

	public void setCurrentmonth(String currentmonth) {
		this.currentmonth = currentmonth;
	}

	public String getId() {
		return this.id;
	}

	/**
	 */

	public void setId(String id) {
		this.id = id;
	}

	public String getIssucess() {
		return this.issucess;
	}

	/**
	 */

	public void setIssucess(String issucess) {
		this.issucess = issucess;
	}

	public String getModelid() {
		return this.modelid;
	}

	/**
	 */

	public void setModelid(String modelid) {
		this.modelid = modelid;
	}

	public String getModelname() {
		return this.modelname;
	}

	/**
	 */

	public void setModelname(String modelname) {
		this.modelname = modelname;
	}

	public String getNotemessage() {
		return this.notemessage;
	}

	/**
	 */

	public void setNotemessage(String notemessage) {
		this.notemessage = notemessage;
	}

	public String getOperatetime() {
		return this.operatetime;
	}

	/**
	 */

	public void setOperatetime(String operatetime) {
		this.operatetime = operatetime;
	}

	public String getOperid() {
		return this.operid;
	}

	/**
	 */

	public void setOperid(String operid) {
		this.operid = operid;
	}

	public String getOpername() {
		return this.opername;
	}

	/**
	 */

	public void setOpername(String opername) {
		this.opername = opername;
	}

	public String getOperremark() {
		return this.operremark;
	}

	/**
	 */

	public void setOperremark(String operremark) {
		this.operremark = operremark;
	}

	public String getRemoteip() {
		return this.remoteip;
	}

	/**
	 */

	public void setRemoteip(String remoteip) {
		this.remoteip = remoteip;
	}

	public String getUrl() {
		return this.url;
	}

	/**
	 */

	public void setUrl(String url) {
		this.url = url;
	}

	public String getUserid() {
		return this.userid;
	}

	/**
	 */

	public void setUserid(String userid) {
		this.userid = userid;
	}

	/*
	 * To add non XDoclet-generated methods, create a file named
	 * xdoclet-TawCommonLogOperatorForm.java containing the additional code and
	 * place it in your metadata/web directory.
	 */
	/**
	 * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
	 *      javax.servlet.http.HttpServletRequest)
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// reset any boolean data types to false

	}

}
