package com.boco.eoms.sheet.nbproducts.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="NBProductsForm" 
 */
public class NBProductsForm
    extends    BaseForm
    implements java.io.Serializable
{
	protected String id;

	protected String nbPName;

	protected String businessDept;

	protected String businessSort;

	protected String recorder;

	protected String recordTime;

	protected String recorderDept;

	protected String recorderContact;

	protected String keyword;

	protected String nbPdescription;

	protected String remarks;

	protected String node;

	protected String deleted;
	
	protected String procode;
	
	protected String code;

	protected String sheetName;
	
	protected String businessSortTwo;

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getProcode() {
		return procode;
	}

	public void setProcode(String procode) {
		this.procode = procode;
	}

	public String getBusinessDept() {
		return businessDept;
	}

	public void setBusinessDept(String businessDept) {
		this.businessDept = businessDept;
	}

	public String getBusinessSort() {
		return businessSort;
	}

	public void setBusinessSort(String businessSort) {
		this.businessSort = businessSort;
	}

	public String getDeleted() {
		return deleted;
	}

	public void setDeleted(String deleted) {
		this.deleted = deleted;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getKeyword() {
		return keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public String getNbPdescription() {
		return nbPdescription;
	}

	public void setNbPdescription(String nbPdescription) {
		this.nbPdescription = nbPdescription;
	}

	public String getNbPName() {
		return nbPName;
	}

	public void setNbPName(String nbPName) {
		this.nbPName = nbPName;
	}

	public String getNode() {
		return node;
	}

	public void setNode(String node) {
		this.node = node;
	}

	public String getRecorder() {
		return recorder;
	}

	public void setRecorder(String recorder) {
		this.recorder = recorder;
	}

	public String getRecorderContact() {
		return recorderContact;
	}

	public void setRecorderContact(String recorderContact) {
		this.recorderContact = recorderContact;
	}

	public String getRecorderDept() {
		return recorderDept;
	}

	public void setRecorderDept(String recorderDept) {
		this.recorderDept = recorderDept;
	}

	public String getRecordTime() {
		return recordTime;
	}

	public void setRecordTime(String recordTime) {
		this.recordTime = recordTime;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getSheetName() {
		return sheetName;
	}

	public void setSheetName(String sheetName) {
		this.sheetName = sheetName;
	}

	public String getBusinessSortTwo() {
		return businessSortTwo;
	}

	public void setBusinessSortTwo(String businessSortTwo) {
		this.businessSortTwo = businessSortTwo;
	}
	

}
