package com.boco.eoms.extra.supplierkpi.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;

import com.boco.eoms.base.util.ApplicationContextHolder;
import com.boco.eoms.base.webapp.form.BaseForm;
import com.boco.eoms.commons.system.dict.dao.hibernate.TawSystemDictTypeDaoHibernate;
import com.boco.eoms.commons.system.dict.exceptions.DictDAOException;

/**
 * Generated by XDoclet/actionform. This class can be further processed with
 * XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 * 
 * @struts.form name="tawSupplierkpiInstanceForm"
 */
public class TawSupplierkpiInstanceForm extends BaseForm implements
		java.io.Serializable {

	protected String id;

	private String kpiItemId;

	protected String appendMan;

	protected String appendManArea;

	protected String appendTime;

	protected String assessContent;

	protected String assessId;

	protected String assessNote;

	protected String assessRole;

	protected String checkContent;

	protected String checkTime;

	protected String checkUser;

	protected String unit;

	protected String dataSource;

	protected String dataType;

	protected String examineContent;

	protected String fillEndTime;

	protected String fillStratTime;

	protected String infoState;

	protected String isImpersonality;

	protected String isPass;

	protected String itemType;

	protected String manufacturerId;

	protected String firstFillTime;

	protected String statictsCycle;

	protected String fillRole;

	protected String timeLatitude;

	protected String manufacturerName;

	protected String serviceType;

	protected String specialType;

	protected String kpiName;

	protected String memo;

	private String updateid;

	private String examineContentJs;

	private String memoJs;
	
	private String treeId;
	
	protected String specialTypeName;
	
	protected String serviceTypeName;	
	
	protected String statictsCycleName;
	
	protected String unitName;
	
	protected String year;
	
	protected String yearMonth;

	public TawSupplierkpiInstanceForm() {
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getAppendMan() {
		return this.appendMan;
	}

	public void setAppendMan(String appendMan) {
		this.appendMan = appendMan;
	}

	public String getAppendManArea() {
		return this.appendManArea;
	}

	public void setAppendManArea(String appendManArea) {
		this.appendManArea = appendManArea;
	}

	public String getAppendTime() {
		return this.appendTime;
	}

	public void setAppendTime(String appendTime) {
		this.appendTime = appendTime;
	}

	public String getAssessContent() {
		return this.assessContent;
	}

	public void setAssessContent(String assessContent) {
		this.assessContent = assessContent;
	}

	public String getAssessId() {
		return this.assessId;
	}

	public void setAssessId(String assessId) {
		this.assessId = assessId;
	}

	public String getAssessNote() {
		return this.assessNote;
	}

	public void setAssessNote(String assessNote) {
		this.assessNote = assessNote;
	}

	public String getAssessRole() {
		return this.assessRole;
	}

	public void setAssessRole(String assessRole) {
		this.assessRole = assessRole;
	}

	public String getCheckContent() {
		return this.checkContent;
	}

	public void setCheckContent(String checkContent) {
		this.checkContent = checkContent;
	}

	public String getCheckTime() {
		return this.checkTime;
	}

	public void setCheckTime(String checkTime) {
		this.checkTime = checkTime;
	}

	public String getCheckUser() {
		return this.checkUser;
	}

	public void setCheckUser(String checkUser) {
		this.checkUser = checkUser;
	}

	public String getUnit() {
		return unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public String getDataSource() {
		return this.dataSource;
	}

	public void setDataSource(String dataSource) {
		this.dataSource = dataSource;
	}

	public String getDataType() {
		return this.dataType;
	}

	public void setDataType(String dataType) {
		this.dataType = dataType;
	}

	public String getExamineContent() {
		return this.examineContent;
	}

	public void setExamineContent(String examineContent) {
		this.examineContent = examineContent;
	}

	public String getFillEndTime() {
		return this.fillEndTime;
	}

	public void setFillEndTime(String fillEndTime) {
		this.fillEndTime = fillEndTime;
	}

	public String getFillStratTime() {
		return this.fillStratTime;
	}

	public void setFillStratTime(String fillStratTime) {
		this.fillStratTime = fillStratTime;
	}

	public String getInfoState() {
		return this.infoState;
	}

	public void setInfoState(String infoState) {
		this.infoState = infoState;
	}

	public String getIsImpersonality() {
		return this.isImpersonality;
	}

	public void setIsImpersonality(String isImpersonality) {
		this.isImpersonality = isImpersonality;
	}

	public String getIsPass() {
		return this.isPass;
	}

	public void setIsPass(String isPass) {
		this.isPass = isPass;
	}

	public String getItemType() {
		return this.itemType;
	}

	public void setItemType(String itemType) {
		this.itemType = itemType;
	}

	public String getManufacturerId() {
		return this.manufacturerId;
	}

	public void setManufacturerId(String manufacturerId) {
		this.manufacturerId = manufacturerId;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public void reset(ActionMapping mapping, HttpServletRequest request) {

	}

	public String getFillRole() {
		return fillRole;
	}

	public void setFillRole(String fillRole) {
		this.fillRole = fillRole;
	}

	public String getFirstFillTime() {
		return firstFillTime;
	}

	public void setFirstFillTime(String firstFillTime) {
		this.firstFillTime = firstFillTime;
	}

	public String getKpiItemId() {
		return kpiItemId;
	}

	public void setKpiItemId(String kpiItemId) {
		this.kpiItemId = kpiItemId;
	}

	public String getStatictsCycle() {
		return statictsCycle;
	}

	public void setStatictsCycle(String statictsCycle) {
		this.statictsCycle = statictsCycle;
	}

	public String getTimeLatitude() {
		return timeLatitude;
	}

	public void setTimeLatitude(String timeLatitude) {
		this.timeLatitude = timeLatitude;
	}

	public String getKpiName() {
		return kpiName;
	}

	public void setKpiName(String kpiName) {
		this.kpiName = kpiName;
	}

	public String getManufacturerName() {
		return manufacturerName;
	}

	public void setManufacturerName(String manufacturerName) {
		this.manufacturerName = manufacturerName;
	}

	public String getServiceType() {
		return serviceType;
	}

	public void setServiceType(String serviceType) {
		this.serviceType = serviceType;
	}

	public String getSpecialType() {
		return specialType;
	}

	public void setSpecialType(String specialType) {
		this.specialType = specialType;
	}

	public String getExamineContentJs() {
		return examineContentJs;
	}

	public void setExamineContentJs(String examineContentJs) {
		this.examineContentJs = examineContentJs;
	}

	public String getMemoJs() {
		return memoJs;
	}

	public void setMemoJs(String memoJs) {
		this.memoJs = memoJs;
	}

	public String getUpdateid() {
		return updateid;
	}

	public void setUpdateid(String updateid) {
		this.updateid = updateid;
	}

	public String getServiceTypeName() throws DictDAOException {
		TawSystemDictTypeDaoHibernate dao = (TawSystemDictTypeDaoHibernate) ApplicationContextHolder
		.getInstance().getBean("ItawSystemDictTypeDao");
		return dao.id2Name(this.getServiceType());
	}

	public void setServiceTypeName(String serviceTypeName) {
		this.serviceTypeName = serviceTypeName;
	}

	public String getSpecialTypeName() throws DictDAOException {
		TawSystemDictTypeDaoHibernate dao = (TawSystemDictTypeDaoHibernate) ApplicationContextHolder
		.getInstance().getBean("ItawSystemDictTypeDao");
         return dao.id2Name(this.getSpecialType());
	}

	public void setSpecialTypeName(String specialTypeName) {
		this.specialTypeName = specialTypeName;
	}

	public String getYear() {
		return year;
	}

	public void setYear(String year) {		
		this.year = year;
	}

	public String getYearMonth() {
		return this.getYear()+"-"+this.getTimeLatitude();		
	}

	public void setYearMonth(String yearMonth) {
		this.yearMonth = yearMonth;
	}

	public String getTreeId() {
		return treeId;
	}

	public void setTreeId(String treeId) {
		this.treeId = treeId;
	}
	
	public String getStatictsCycleName() throws DictDAOException {
		TawSystemDictTypeDaoHibernate dao = (TawSystemDictTypeDaoHibernate) ApplicationContextHolder
		.getInstance().getBean("ItawSystemDictTypeDao");
         return dao.id2Name(this.statictsCycle);
	}	
	
	public String getUnitName() throws DictDAOException {
		TawSystemDictTypeDaoHibernate dao = (TawSystemDictTypeDaoHibernate) ApplicationContextHolder
		.getInstance().getBean("ItawSystemDictTypeDao");
         return dao.id2Name(this.unit);
	}	
	

}
