package com.boco.eoms.extra.supplierkpi.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="tawSupplierkpiInstanceAssForm"
 */
public class TawSupplierkpiInstanceAssForm
        extends BaseForm
        implements java.io.Serializable {

    protected String assessAttitude;

    protected String assessLevel;

    protected String subRole;

    protected String assessStatus;

    protected String assessTime;

    protected String id;

    protected String instanceId;

    protected String realAssessor;

    protected String serviceType;

    protected String specialType;

    protected String supplierId;

    protected String timeLatitude;

    protected String degree;

    protected String year;

    public String getYear() {
        return year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    public String getDegree() {
        return degree;
    }

    public void setDegree(String degree) {
        this.degree = degree;
    }

    /**
     * Default empty constructor.
     */
    public TawSupplierkpiInstanceAssForm() {
    }

    public String getAssessAttitude() {
        return this.assessAttitude;
    }

    /**
     * @struts.validator type="required"
     */

    public void setAssessAttitude(String assessAttitude) {
        this.assessAttitude = assessAttitude;
    }

    public String getAssessLevel() {
        return this.assessLevel;
    }

    /**
     * @struts.validator type="required"
     */

    public void setAssessLevel(String assessLevel) {
        this.assessLevel = assessLevel;
    }

    public String getSubRole() {
        return this.subRole;
    }

    /**
     * @struts.validator type="required"
     */

    public void setSubRole(String subRole) {
        this.subRole = subRole;
    }

    public String getAssessStatus() {
        return this.assessStatus;
    }

    /**
     * @struts.validator type="required"
     */

    public void setAssessStatus(String assessStatus) {
        this.assessStatus = assessStatus;
    }

    public String getAssessTime() {
        return this.assessTime;
    }

    /**
     * @struts.validator type="required"
     */

    public void setAssessTime(String assessTime) {
        this.assessTime = assessTime;
    }

    public String getId() {
        return this.id;
    }

    /**
     *
     */

    public void setId(String id) {
        this.id = id;
    }

    public String getInstanceId() {
        return this.instanceId;
    }

    /**
     * @struts.validator type="required"
     */

    public void setInstanceId(String instanceId) {
        this.instanceId = instanceId;
    }

    public String getRealAssessor() {
        return this.realAssessor;
    }

    /**
     * @struts.validator type="required"
     */

    public void setRealAssessor(String realAssessor) {
        this.realAssessor = realAssessor;
    }

    public String getServiceType() {
        return this.serviceType;
    }

    /**
     * @struts.validator type="required"
     */

    public void setServiceType(String serviceType) {
        this.serviceType = serviceType;
    }

    public String getSpecialType() {
        return this.specialType;
    }

    /**
     * @struts.validator type="required"
     */

    public void setSpecialType(String specialType) {
        this.specialType = specialType;
    }

    public String getSupplierId() {
        return this.supplierId;
    }

    /**
     * @struts.validator type="required"
     */

    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId;
    }

    public String getTimeLatitude() {
        return this.timeLatitude;
    }

    /**
     * @struts.validator type="required"
     */

    public void setTimeLatitude(String timeLatitude) {
        this.timeLatitude = timeLatitude;
    }

        /* To add non XDoclet-generated methods, create a file named
           xdoclet-TawSupplierkpiInstanceAssForm.java 
           containing the additional code and place it in your metadata/web directory.
        */

    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     * javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

}
