package com.boco.eoms.extra.supplierkpi.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="tawSupplierkpiInfoForm"
 */
public class TawSupplierkpiInfoForm
        extends BaseForm
        implements java.io.Serializable {

    protected String id;

    protected String supplierContact;

    protected String supplierLinkman;

    protected String supplierName;

    /**
     * Default empty constructor.
     */
    public TawSupplierkpiInfoForm() {
    }

    public String getId() {
        return this.id;
    }

    /**
     *
     */

    public void setId(String id) {
        this.id = id;
    }

    public String getSupplierContact() {
        return this.supplierContact;
    }

    /**
     * @struts.validator type="required"
     */

    public void setSupplierContact(String supplierContact) {
        this.supplierContact = supplierContact;
    }

    public String getSupplierLinkman() {
        return this.supplierLinkman;
    }

    /**
     * @struts.validator type="required"
     */

    public void setSupplierLinkman(String supplierLinkman) {
        this.supplierLinkman = supplierLinkman;
    }

    public String getSupplierName() {
        return this.supplierName;
    }

    /**
     * @struts.validator type="required"
     */

    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

        /* To add non XDoclet-generated methods, create a file named
           xdoclet-TawSupplierkpiInfoForm.java 
           containing the additional code and place it in your metadata/web directory.
        */

    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     * javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

}
