package com.boco.eoms.extra.supplierkpi.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="tawSupplierkpiTemplateAssessForm" 
 */
public class TawSupplierkpiTemplateAssessForm
    extends    BaseForm
    implements java.io.Serializable
{

    protected String assessAttitude;

    protected String assessLevel;

    protected String assessRole;

    protected int assessStatus;

    protected String assessTime;

    protected String id;

    protected String realAssessor;

    protected String templateId;
    
    protected int isUpdate;
    
    protected int isKpiChanged;
    
    public int getIsKpiChanged() {
		return isKpiChanged;
	}

	public void setIsKpiChanged(int isKpiChanged) {
		this.isKpiChanged = isKpiChanged;
	}

	public int getIsUpdate() {
		return isUpdate;
	}

	public void setIsUpdate(int isUpdate) {
		this.isUpdate = isUpdate;
	}

	/** Default empty constructor. */
    public TawSupplierkpiTemplateAssessForm() {}

    public String getAssessAttitude()
    {
        return this.assessAttitude;
    }
   /**
    * @struts.validator type="required"
    */

    public void setAssessAttitude( String assessAttitude )
    {
        this.assessAttitude = assessAttitude;
    }

    public String getAssessLevel()
    {
        return this.assessLevel;
    }
   /**
    * @struts.validator type="required"
    */

    public void setAssessLevel( String assessLevel )
    {
        this.assessLevel = assessLevel;
    }

    public String getAssessRole()
    {
        return this.assessRole;
    }
   /**
    * @struts.validator type="required"
    */

    public void setAssessRole( String assessRole )
    {
        this.assessRole = assessRole;
    }

    public int getAssessStatus()
    {
        return this.assessStatus;
    }
   /**
    * @struts.validator type="required"
    */

    public void setAssessStatus( int assessStatus )
    {
        this.assessStatus = assessStatus;
    }

    public String getAssessTime()
    {
        return this.assessTime;
    }
   /**
    * @struts.validator type="required"
    */

    public void setAssessTime( String assessTime )
    {
        this.assessTime = assessTime;
    }

    public String getId()
    {
        return this.id;
    }
   /**
    */

    public void setId( String id )
    {
        this.id = id;
    }

    public String getRealAssessor()
    {
        return this.realAssessor;
    }
   /**
    * @struts.validator type="required"
    */

    public void setRealAssessor( String realAssessor )
    {
        this.realAssessor = realAssessor;
    }

    public String getTemplateId()
    {
        return this.templateId;
    }
   /**
    * @struts.validator type="required"
    */

    public void setTemplateId( String templateId )
    {
        this.templateId = templateId;
    }

        /* To add non XDoclet-generated methods, create a file named
           xdoclet-TawSupplierkpiTemplateAssessForm.java 
           containing the additional code and place it in your metadata/web directory.
        */
    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     *                                                javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

}
