package com.boco.eoms.extra.supplierkpi.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="tawSupplierkpiItemTypeForm"
 */
public class TawSupplierkpiItemTypeForm
        extends BaseForm
        implements java.io.Serializable {

    protected String dictName;

    protected String dictRemark;

    protected String id;

    /**
     * Default empty constructor.
     */
    public TawSupplierkpiItemTypeForm() {
    }

    public String getDictName() {
        return this.dictName;
    }

    /**
     * @struts.validator type="required"
     */

    public void setDictName(String dictName) {
        this.dictName = dictName;
    }

    public String getDictRemark() {
        return this.dictRemark;
    }

    /**
     * @struts.validator type="required"
     */

    public void setDictRemark(String dictRemark) {
        this.dictRemark = dictRemark;
    }

    public String getId() {
        return this.id;
    }

    /**
     *
     */

    public void setId(String id) {
        this.id = id;
    }

        /* To add non XDoclet-generated methods, create a file named
           xdoclet-TawSupplierkpiItemTypeForm.java 
           containing the additional code and place it in your metadata/web directory.
        */

    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     * javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

}
