package com.boco.eoms.extra.supplierkpi.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="tawSupplierkpiLogForm" 
 */
public class TawSupplierkpiLogForm
    extends    BaseForm
    implements java.io.Serializable
{

    protected String deleted;

    protected String id;

    protected String operator;
    
    protected String operatorName;

    protected String operContent;

    protected String operTime;

    protected String operType;
    
    protected String serviceType;
    
    protected String specialType;

    /** Default empty constructor. */
    public TawSupplierkpiLogForm() {}

    public String getDeleted()
    {
        return this.deleted;
    }
   /**
    * @struts.validator type="required"
    */

    public void setDeleted( String deleted )
    {
        this.deleted = deleted;
    }

    public String getId()
    {
        return this.id;
    }
   /**
    */

    public void setId( String id )
    {
        this.id = id;
    }

    public String getOperator()
    {
        return this.operator;
    }
   /**
    * @struts.validator type="required"
    */

    public void setOperator( String operator )
    {
        this.operator = operator;
    }

    public String getOperatorName() {
    	return operatorName;
    }

    public void setOperatorName(String operatorName) {
    	this.operatorName = operatorName;
    }

	public String getOperContent()
    {
        return this.operContent;
    }
   /**
    * @struts.validator type="required"
    */

    public void setOperContent( String operContent )
    {
        this.operContent = operContent;
    }

    public String getOperTime()
    {
        return this.operTime;
    }
   /**
    * @struts.validator type="required"
    */

    public void setOperTime( String operTime )
    {
        this.operTime = operTime;
    }

    public String getOperType()
    {
        return this.operType;
    }
   /**
    * @struts.validator type="required"
    */

    public void setOperType( String operType )
    {
        this.operType = operType;
    }
    
    public String getServiceType() {
    	return serviceType;
    }

    public void setServiceType(String serviceType) {
    	this.serviceType = serviceType;
    }

	public String getSpecialType()
    {
    	return specialType;
    }

    public void setSpecialType(String specialType) {
    	this.specialType = specialType;
    }

	/* To add non XDoclet-generated methods, create a file named
           xdoclet-TawSupplierkpiLogForm.java 
           containing the additional code and place it in your metadata/web directory.
        */
    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     *                                                javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

}
