package com.boco.eoms.extra.supplierkpi.webapp.form;

import java.sql.Timestamp;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;

import com.boco.eoms.base.util.ApplicationContextHolder;
import com.boco.eoms.base.webapp.form.BaseForm;
import com.boco.eoms.commons.system.dict.dao.hibernate.TawSystemDictTypeDaoHibernate;
import com.boco.eoms.commons.system.dict.exceptions.DictDAOException;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="tawSupplierkpiAssessInstanceForm"
 */
public class TawSupplierkpiAssessInstanceForm
        extends BaseForm
        implements java.io.Serializable {

    protected String assessLevel;

    protected int assessStatus;

    protected String createTime;

    protected String creator;

    protected String id;

    protected String serviceType;

    protected String specialType;

    protected String supplierId;

    protected String templateName;

    private String timeLatitude;
    private Timestamp assessTime;
    private String realAssessor;
    private String assessAttitude;
    private String subRole;

    protected String id2specialType;
    protected String id2serviceType;

    /**
     * Default empty constructor.
     */
    public TawSupplierkpiAssessInstanceForm() {
    }

    public String getId2specialType() throws DictDAOException {
        TawSystemDictTypeDaoHibernate dao = (TawSystemDictTypeDaoHibernate) ApplicationContextHolder
                .getInstance().getBean("ItawSystemDictTypeDao");
        return dao.id2Name(this.getSpecialType());
    }

    public String getId2serviceType() throws DictDAOException {
        TawSystemDictTypeDaoHibernate dao = (TawSystemDictTypeDaoHibernate) ApplicationContextHolder
                .getInstance().getBean("ItawSystemDictTypeDao");
        return dao.id2Name(this.getServiceType());
    }

    public String getAssessLevel() {
        return this.assessLevel;
    }

    /**
     * @struts.validator type="required"
     */

    public void setAssessLevel(String assessLevel) {
        this.assessLevel = assessLevel;
    }

    public int getAssessStatus() {
        return this.assessStatus;
    }

    /**
     * @struts.validator type="required"
     */

    public void setAssessStatus(int assessStatus) {
        this.assessStatus = assessStatus;
    }

    public String getCreateTime() {
        return this.createTime;
    }

    /**
     * @struts.validator type="required"
     */

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getCreator() {
        return this.creator;
    }

    /**
     * @struts.validator type="required"
     */

    public void setCreator(String creator) {
        this.creator = creator;
    }

    public String getId() {
        return this.id;
    }

    /**
     *
     */

    public void setId(String id) {
        this.id = id;
    }

    public String getServiceType() {
        return this.serviceType;
    }

    /**
     * @struts.validator type="required"
     */

    public void setServiceType(String serviceType) {
        this.serviceType = serviceType;
    }

    public String getSpecialType() {
        return this.specialType;
    }

    /**
     * @struts.validator type="required"
     */

    public void setSpecialType(String specialType) {
        this.specialType = specialType;
    }

    public String getSupplierId() {
        return this.supplierId;
    }

    /**
     * @struts.validator type="required"
     */

    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId;
    }

    public String getTemplateName() {
        return this.templateName;
    }

    /**
     * @struts.validator type="required"
     */

    public void setTemplateName(String templateName) {
        this.templateName = templateName;
    }

    public String getAssessAttitude() {
        return assessAttitude;
    }

    public void setAssessAttitude(String assessAttitude) {
        this.assessAttitude = assessAttitude;
    }

    public Timestamp getAssessTime() {
        return assessTime;
    }

    public void setAssessTime(Timestamp assessTime) {
        this.assessTime = assessTime;
    }

    public String getRealAssessor() {
        return realAssessor;
    }

    public void setRealAssessor(String realAssessor) {
        this.realAssessor = realAssessor;
    }

    public String getSubRole() {
        return subRole;
    }

    public void setSubRole(String subRole) {
        this.subRole = subRole;
    }

    public String getTimeLatitude() {
        return timeLatitude;
    }

    public void setTimeLatitude(String timeLatitude) {
        this.timeLatitude = timeLatitude;
    }

        /* To add non XDoclet-generated methods, create a file named
           xdoclet-TawSupplierkpiAssessInstanceForm.java 
           containing the additional code and place it in your metadata/web directory.
        */

    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     * javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

}
