package com.boco.eoms.commons.system.area.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="tawSystemAreaForm" 
 */
public class TawSystemAreaForm
    extends    BaseForm
    implements java.io.Serializable
{

    protected String areaid;

    protected String areaname;

    protected String id;

    protected String leaf;

    protected String remark;
    
    protected String parentAreaid;
    
    protected String ordercode;
    
    protected String areacode; 
        
    protected String oldAreaName;   

    protected String capital;    

	public String getOldAreaName() {
		return oldAreaName;
	}

	public void setOldAreaName(String oldAreaName) {
		this.oldAreaName = oldAreaName;
	}

	public String getOrdercode() {
		return ordercode;
	}

	public void setOrdercode(String ordercode) {
		this.ordercode = ordercode;
	}

	public String getParentAreaid() {
		return parentAreaid;
	}

	public void setParentAreaid(String parentAreaid) {
		this.parentAreaid = parentAreaid;
	}

	/** Default empty constructor. */
    public TawSystemAreaForm() {}

    public String getAreaid()
    {
        return this.areaid;
    }
   /**
    */

    public void setAreaid( String areaid )
    {
        this.areaid = areaid;
    }

    public String getAreaname()
    {
        return this.areaname;
    }
   /**
    */

    public void setAreaname( String areaname )
    {
        this.areaname = areaname;
    }

    public String getId()
    {
        return this.id;
    }
   /**
    */

    public void setId( String id )
    {
        this.id = id;
    }

    public String getLeaf()
    {
        return this.leaf;
    }
   /**
    */

    public void setLeaf( String leaf )
    {
        this.leaf = leaf;
    }

    public String getRemark()
    {
        return this.remark;
    }
   /**
    */

    public void setRemark( String remark )
    {
        this.remark = remark;
    }

        /* To add non XDoclet-generated methods, create a file named
           xdoclet-TawSystemAreaForm.java 
           containing the additional code and place it in your metadata/web directory.
        */
    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     *                                                javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

	public String getAreacode() {
		return areacode;
	}

	public void setAreacode(String areacode) {
		this.areacode = areacode;
	}

	//是否是省会或直辖市的标志位
	public String getCapital() {
		return capital;
	}

	public void setCapital(String capital) {
		this.capital = capital;
	}
	
}
