package com.boco.eoms.commons.job.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with
 * XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 * 
 * @struts.form name="tawCommonsJobsortForm"
 */
public class TawCommonsJobsortForm extends BaseForm implements
		java.io.Serializable {
	 /**
     * 删除标志
     */
	protected String deleted = "0";
	 /**
     * ID
     */
	protected String id;
	 /**
     * 任务执行类名
     */
	protected String jobClassName;
	 /**
     * 任务类型名称
     */
	protected String jobSortName;
	 /**
     * 备注
     */
	protected String remark;
	 /**
     * 任务最大允许执行时间
     */
	protected String maxExecuteTime;

	/** Default empty constructor. */
	public TawCommonsJobsortForm() {
	}

	public String getDeleted() {
		return this.deleted;
	}

	/**
	 */

	public void setDeleted(String deleted) {
		this.deleted = deleted;
	}

	public String getId() {
		return this.id;
	}

	/**
	 */

	public void setId(String id) {
		this.id = id;
	}

	public String getJobClassName() {
		return this.jobClassName;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setJobClassName(String jobClassName) {
		this.jobClassName = jobClassName;
	}

	public String getJobSortName() {
		return this.jobSortName;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setJobSortName(String jobSortName) {
		this.jobSortName = jobSortName;
	}

	public String getRemark() {
		return this.remark;
	}

	/**
	 */

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getMaxExecuteTime() {
		return this.maxExecuteTime;
	}

	/**
	 */

	public void setMaxExecuteTime(String maxExecuteTime) {
		this.maxExecuteTime = maxExecuteTime;
	}

	/*
	 * To add non XDoclet-generated methods, create a file named
	 * xdoclet-TawCommonsJobsortForm.java containing the additional code and
	 * place it in your metadata/web directory.
	 */
	/**
	 * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
	 *      javax.servlet.http.HttpServletRequest)
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// reset any boolean data types to false

	}

}
