package com.boco.eoms.commons.job.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with
 * XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 * 
 * @struts.form name="tawCommonsJobsubscibeForm"
 */
public class TawCommonsJobsubscibeForm extends BaseForm implements
		java.io.Serializable {
    /**
     * 删除标志
     */
	protected String deleted = "0";
    /**
     * ID
     */
	protected String id;
    /**
     * 任务类型ID
     */
	protected String jobSortId;
    /**
     * 任务周期
     */
	protected String jobCycle;
    /**
     * 任务类型：simple或者cron
     */
	protected String jobType;
    /**
     * 订阅号
     */
	protected String subId;
    /**
     * 订阅部门
     */
	protected String subscriberDeptId;
    /**
     * 订阅者
     */
	protected String subscriberId;
    /**
     * 订阅时间
     */
	protected String subscribeTime;

	/** Default empty constructor. */
	public TawCommonsJobsubscibeForm() {
	}

	public String getDeleted() {
		return this.deleted;
	}

	/**
	 */

	public void setDeleted(String deleted) {
		this.deleted = deleted;
	}

	public String getId() {
		return this.id;
	}

	/**
	 */

	public void setId(String id) {
		this.id = id;
	}

	public String getJobSortId() {
		return this.jobSortId;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setJobSortId(String jobSortId) {
		this.jobSortId = jobSortId;
	}

	public String getJobCycle() {
		return this.jobCycle;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setJobCycle(String jobCycle) {
		this.jobCycle = jobCycle;
	}

	public String getJobType() {
		return this.jobType;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setJobType(String jobType) {
		this.jobType = jobType;
	}

	public String getSubId() {
		return this.subId;
	}

	/**
	 */

	public void setSubId(String subId) {
		this.subId = subId;
	}

	public String getSubscriberDeptId() {
		return this.subscriberDeptId;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setSubscriberDeptId(String subscriberDeptId) {
		this.subscriberDeptId = subscriberDeptId;
	}

	public String getSubscriberId() {
		return this.subscriberId;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setSubscriberId(String subscriberId) {
		this.subscriberId = subscriberId;
	}

	public String getSubscribeTime() {
		return this.subscribeTime;
	}

	/**
	 */

	public void setSubscribeTime(String subscribeTime) {
		this.subscribeTime = subscribeTime;
	}

	/*
	 * To add non XDoclet-generated methods, create a file named
	 * xdoclet-TawCommonsJobsubscibeForm.java containing the additional code and
	 * place it in your metadata/web directory.
	 */
	/**
	 * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
	 *      javax.servlet.http.HttpServletRequest)
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// reset any boolean data types to false

	}

}
