package com.boco.eoms.commons.workdayset.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="tawWorkdaySetForm" 
 */
public class TawWorkdaySetForm
    extends    BaseForm
    implements java.io.Serializable
{

    protected String areaId;

    protected String createTime;

    protected String deleted;

    protected String endTime1;

    protected String id;

    protected String startTime1;

    protected String status;

    protected String userId;

    protected String workDate;
    
    protected String startTime2;
    
    protected String startTime3;
    
    protected String endTime2;
    
    protected String endTime3;
    
    protected String cover;
    protected String selected;

    /** Default empty constructor. */
    public TawWorkdaySetForm() {}

    public String getSelected()
    {
        return this.selected;
    }
   /**
    */

    public void setSelected( String selected )
    {
        this.selected = selected;
    }
    public String getCover()
    {
        return this.cover;
    }
   /**
    */

    public void setCover( String cover )
    {
        this.cover = cover;
    }
    public String getAreaId()
    {
        return this.areaId;
    }
   /**
    */

    public void setAreaId( String areaId )
    {
        this.areaId = areaId;
    }

    public String getCreateTime()
    {
        return this.createTime;
    }
   /**
    */

    public void setCreateTime( String createTime )
    {
        this.createTime = createTime;
    }

    public String getDeleted()
    {
        return this.deleted;
    }
   /**
    */

    public void setDeleted( String deleted )
    {
        this.deleted = deleted;
    }

    public String getEndTime1()
    {
        return this.endTime1;
    }
   /**
    */

    public void setEndTime1( String endTime )
    {
        this.endTime1 = endTime;
    }
    public String getEndTime2()
    {
        return this.endTime2;
    }
   /**
    */

    public void setEndTime2( String endTime )
    {
        this.endTime2 = endTime;
    }

    public String getEndTime3()
    {
        return this.endTime3;
    }
   /**
    */

    public void setEndTime3( String endTime )
    {
        this.endTime3 = endTime;
    }
    public String getId()
    {
        return this.id;
    }
   /**
    */

    public void setId( String id )
    {
        this.id = id;
    }

    public String getStartTime1()
    {
        return this.startTime1;
    }
   /**
    */

    public void setStartTime1( String startTime )
    {
        this.startTime1 = startTime;
    }
    
    public String getStartTime2()
    {
        return this.startTime2;
    }
   /**
    */

    public void setStartTime2( String startTime )
    {
        this.startTime2 = startTime;
    }
    public String getStartTime3()
    {
        return this.startTime3;
    }
   /**
    */

    public void setStartTime3( String startTime )
    {
        this.startTime3 = startTime;
    }

    public String getStatus()
    {
        return this.status;
    }
   /**
    */

    public void setStatus( String status )
    {
        this.status = status;
    }

    public String getUserId()
    {
        return this.userId;
    }
   /**
    */

    public void setUserId( String userId )
    {
        this.userId = userId;
    }

    public String getWorkDate()
    {
        return this.workDate;
    }
   /**
    */

    public void setWorkDate( String workDate )
    {
        this.workDate = workDate;
    }

        /* To add non XDoclet-generated methods, create a file named
           xdoclet-TawWorkdaySetForm.java 
           containing the additional code and place it in your metadata/web directory.
        */
    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     *                                                javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

}
