package com.boco.eoms.commons.system.cptroom.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with
 * XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 * 
 * @struts.form name="tawSystemCptroomForm"
 */
public class TawSystemCptroomForm extends BaseForm implements
		java.io.Serializable {

	protected String address;

	protected String deleted;

	protected String deptid;

	protected String endtime;

	protected String fax;

	protected String id;

	protected String manager;

	protected String mobile;

	protected String notes;

	protected String phone;

	protected String roomname;

	protected String tempmanager;

	protected String leaf;

	protected String parentid;

	protected String managerName;

	protected String tempmanagerName;

	protected String deptName;

	/** Default empty constructor. */
	public TawSystemCptroomForm() {
	}

	public String getAddress() {
		return this.address;
	}

	/**
	 */

	public void setAddress(String address) {
		this.address = address;
	}

	public String getDeleted() {
		return this.deleted;
	}

	/**
	 */

	public void setDeleted(String deleted) {
		this.deleted = deleted;
	}

	public String getDeptid() {
		return this.deptid;
	}

	/**
	 */

	public void setDeptid(String deptid) {
		this.deptid = deptid;
	}

	public String getEndtime() {
		return this.endtime;
	}

	/**
	 */

	public void setEndtime(String endtime) {
		this.endtime = endtime;
	}

	public String getFax() {
		return this.fax;
	}

	/**
	 */

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getId() {
		return this.id;
	}

	/**
	 */

	public void setId(String id) {
		this.id = id;
	}

	public String getManager() {
		return this.manager;
	}

	/**
	 */

	public void setManager(String manager) {
		this.manager = manager;
	}

	public String getMobile() {
		return this.mobile;
	}

	/**
	 */

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getNotes() {
		return this.notes;
	}

	/**
	 */

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getPhone() {
		return this.phone;
	}

	/**
	 */

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getRoomname() {
		return this.roomname;
	}

	/**
	 */

	public void setRoomname(String roomname) {
		this.roomname = roomname;
	}

	public String getTempmanager() {
		return this.tempmanager;
	}

	/**
	 */

	public void setTempmanager(String tempmanager) {
		this.tempmanager = tempmanager;
	}

	public String getLeaf() {
		return this.leaf;
	}

	/**
	 */

	public void setLeaf(String leaf) {
		this.leaf = leaf;
	}

	public String getParentid() {
		return this.parentid;
	}

	/**
	 */

	public void setParentid(String parentid) {
		this.parentid = parentid;
	}

	public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getManagerName() {
		return managerName;
	}

	public void setManagerName(String managerName) {
		this.managerName = managerName;
	}

	public String getTempmanagerName() {
		return tempmanagerName;
	}

	public void setTempmanagerName(String tempmanagerName) {
		this.tempmanagerName = tempmanagerName;
	}

	/*
	 * To add non XDoclet-generated methods, create a file named
	 * xdoclet-TawSystemCptroomForm.java containing the additional code and
	 * place it in your metadata/web directory.
	 */
	/**
	 * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
	 *      javax.servlet.http.HttpServletRequest)
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// reset any boolean data types to false

	}

}
