package com.boco.eoms.commons.system.priv.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with
 * XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 * 
 * @struts.form name="tawSystemPrivUserAssignForm"
 */
public class TawSystemPrivUserAssignForm extends BaseForm implements
		java.io.Serializable {

	protected String currentprivid;

	protected String currentprivname;

	protected String hide;

	protected String id;

	protected String isonepriv;

	protected String leaf;

	protected String ordercode;

	protected String parentprivid;

	protected String parentprivname;

	protected String remark;

	protected String userid;

	protected String hrefTarget;
	
	protected String orderby;
	
	public String getOrderby() {
		if(orderby==null){
			orderby="20";
		}
		return orderby;
	}

	public void setOrderby(String orderby) {
		this.orderby = orderby;
	}

	public String getHrefTarget() {
		return hrefTarget;
	}

	public void setHrefTarget(String hrefTarget) {
		this.hrefTarget = hrefTarget;
	}

	/** Default empty constructor. */
	public TawSystemPrivUserAssignForm() {
	}

	public String getCurrentprivid() {
		return this.currentprivid;
	}

	/**
	 */

	public void setCurrentprivid(String currentprivid) {
		this.currentprivid = currentprivid;
	}

	public String getCurrentprivname() {
		return this.currentprivname;
	}

	/**
	 */

	public void setCurrentprivname(String currentprivname) {
		this.currentprivname = currentprivname;
	}

	public String getHide() {
		return this.hide;
	}

	/**
	 */

	public void setHide(String hide) {
		this.hide = hide;
	}

	public String getId() {
		return this.id;
	}

	/**
	 */

	public void setId(String id) {
		this.id = id;
	}

	public String getIsonepriv() {
		return this.isonepriv;
	}

	/**
	 */

	public void setIsonepriv(String isonepriv) {
		this.isonepriv = isonepriv;
	}

	public String getLeaf() {
		return this.leaf;
	}

	/**
	 */

	public void setLeaf(String leaf) {
		this.leaf = leaf;
	}

	public String getOrdercode() {
		return this.ordercode;
	}

	/**
	 */

	public void setOrdercode(String ordercode) {
		this.ordercode = ordercode;
	}

	public String getParentprivid() {
		return this.parentprivid;
	}

	/**
	 */

	public void setParentprivid(String parentprivid) {
		this.parentprivid = parentprivid;
	}

	public String getParentprivname() {
		return this.parentprivname;
	}

	/**
	 */

	public void setParentprivname(String parentprivname) {
		this.parentprivname = parentprivname;
	}

	public String getRemark() {
		return this.remark;
	}

	/**
	 */

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getUserid() {
		return this.userid;
	}

	/**
	 */

	public void setUserid(String userid) {
		this.userid = userid;
	}

	/*
	 * To add non XDoclet-generated methods, create a file named
	 * xdoclet-TawSystemPrivUserAssignForm.java containing the additional code
	 * and place it in your metadata/web directory.
	 */
	/**
	 * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
	 *      javax.servlet.http.HttpServletRequest)
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// reset any boolean data types to false

	}

}
