package com.boco.eoms.commons.system.priv.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import com.boco.eoms.base.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with
 * XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 * 
 * @struts.form name="tawSystemPrivOperationForm"
 */
public class TawSystemPrivOperationForm extends BaseForm implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8703648258488023594L;

	protected String code;

	protected String id;

	protected String isApp;

	protected String name;

	protected String parentcode;

	protected String parentName;

	protected String remark;

	protected String url;

	protected String deleted;
	/**
	 * 登陆方式
	 */
	
	protected String loginType;

	/**
	 * 隐藏标记
	 */
	protected String hided;

	protected String orderby;

	public String getOrderby() {
		if (orderby == null) {
			orderby = "20";
		}
		return orderby;
	}

	public void setOrderby(String orderby) {
		this.orderby = orderby;
	}

	public String getDeleted() {
		return deleted;
	}

	public void setDeleted(String deleted) {
		this.deleted = deleted;
	}

	/** Default empty constructor. */
	public TawSystemPrivOperationForm() {
	}

	public String getCode() {
		return this.code;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setCode(String code) {
		this.code = code;
	}

	public String getId() {
		return this.id;
	}

	/**
	 */

	public void setId(String id) {
		this.id = id;
	}

	public String getIsApp() {
		return this.isApp;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setIsApp(String isApp) {
		this.isApp = isApp;
	}

	public String getName() {
		return this.name;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setName(String name) {
		this.name = name;
	}

	public String getParentcode() {
		return this.parentcode;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setParentcode(String parentcode) {
		this.parentcode = parentcode;
	}

	public String getRemark() {
		return this.remark;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getUrl() {
		return this.url;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setUrl(String url) {
		this.url = url;
	}

	/*
	 * To add non XDoclet-generated methods, create a file named
	 * xdoclet-TawSystemPrivOperationForm.java containing the additional code
	 * and place it in your metadata/web directory.
	 */
	/**
	 * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
	 *      javax.servlet.http.HttpServletRequest)
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// reset any boolean data types to false

	}

	public String getParentName() {
		return parentName;
	}

	public void setParentName(String parentName) {
		this.parentName = parentName;
	}

	/**
	 * @return the hided
	 */
	public String getHided() {
		return hided;
	}

	/**
	 * @param hided the hided to set
	 */
	public void setHided(String hided) {
		this.hided = hided;
	}

	public String getLoginType() {
		return loginType;
	}

	public void setLoginType(String loginType) {
		this.loginType = loginType;
	}

}
